Repository openhab/openhab-webui, pull requests merged in 2020-12, with the labels that each got.

#593 Don't include empty equipment when only Points are added
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-thing.vue
Labels: bug

#595 Fix group settings not appearing when creating a group
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
Labels: bug

#596 Fix invert not applied on f7-icons in badges
  bundles/org.openhab.ui/web/src/components/cards/glance/location/measurement-badge.vue
  bundles/org.openhab.ui/web/src/components/cards/glance/location/status-badge.vue
Labels: bug

#599 Add options to oh-map-page & fix initial positioning
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/map/index.js
  bundles/org.openhab.ui/web/src/components/widgets/map/index.js
  bundles/org.openhab.ui/web/src/components/widgets/map/oh-map-page.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/map/map-edit.vue
Labels: enhancement

#590 CometVisu fixes
  bundles/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/CometVisuTile.java
  bundles/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/util/SseUtil.java
  bundles/org.openhab.ui.cometvisu/src/main/resources/404.html
Labels: bug, cometvisu ui

#631 Misc styling fixes
  bundles/org.openhab.ui/web/src/components/cards/model-card.vue
  bundles/org.openhab.ui/web/src/pages/about.vue
  bundles/org.openhab.ui/web/src/pages/home.vue
  bundles/org.openhab.ui/web/src/pages/home/homecards-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: enhancement

#632 Support Ctrl+click in Inbox list
  bundles/org.openhab.ui/web/src/pages/settings/things/inbox/inbox-list.vue
Labels: enhancement

#633 [Main UI/HABPanel] Mobile app interface, part 2
  bundles/org.openhab.ui.habpanel/web/app/menu/menu.controller.js
  bundles/org.openhab.ui.habpanel/web/app/menu/menu.html
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: enhancement
