Repository openhab/openhab-webui, pull requests merged in 2021-01, with the labels that each got.

#727 Add all the doors
  bundles/org.openhab.ui/web/src/components/cards/glance/location/status-badge.vue
Labels: rebuild

#803 Setup wizard: add empty values for language, region
  bundles/org.openhab.ui/web/src/assets/i18n/setup-wizard/en.json
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-location.vue
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: bug, main ui

#804 Don't propagate loop to child widgets contexts
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: bug, main ui

#805 Don't update the model until save
  bundles/org.openhab.ui/web/src/components/model/item-details.vue
Labels: bug, main ui

#806 Don't generate empty tags when clearing semantics in picker
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
Labels: bug, main ui

#807 Handle invalid links
  bundles/org.openhab.ui/web/src/components/model/link-details.vue
Labels: bug, main ui

#814 Upgrade ECharts to v5, add support for ECharts gauge & chart widget
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/page.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/chart.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/index.js
  bundles/org.openhab.ui/web/src/components/config/editor/hint-components.js
  bundles/org.openhab.ui/web/src/components/thing/zwave/zwave-network.vue
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/chart/oh-chart-page.vue
  bundles/org.openhab.ui/web/src/components/widgets/chart/series/oh-data-series.js
  bundles/org.openhab.ui/web/src/components/widgets/system/index.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart-component.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart.vue
Labels: enhancement, main ui

#850 Add support for pie charts
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/index.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart-component.vue
Labels: enhancement, main ui
