Repository openhab/openhab-webui, pull requests merged in 2021-04, with the labels that each got.

#815 Adjusted schedule ui to use the new rest service for rule preview
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/pages/settings/schedule/schedule.vue
Labels: rebuild

#1013 fix small bug in widget mixin
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: bug, main ui

#1029 Implement link editable flag
  bundles/org.openhab.ui/web/src/components/model/link-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
Labels: enhancement, main ui
