Repository openhab/openhab-webui, pull requests merged in 2022-12, with the labels that each got.

#1548 [BasicUI] Fix the color picker
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#1564 [MainUI] Fix oh-trend sampling property
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-trend.vue
Labels: bug, main ui

#1556 [MainUI] Add possibility to edit JSON variable keys in widgets
  bundles/org.openhab.ui/doc/components/oh-aggregate-series.md
  bundles/org.openhab.ui/doc/components/oh-button.md
  bundles/org.openhab.ui/doc/components/oh-calendar-axis.md
  bundles/org.openhab.ui/doc/components/oh-calendar-series.md
  bundles/org.openhab.ui/doc/components/oh-cell.md
  bundles/org.openhab.ui/doc/components/oh-clock-card.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-cell.md
  bundles/org.openhab.ui/doc/components/oh-data-series.md
  bundles/org.openhab.ui/doc/components/oh-gauge-card.md
  bundles/org.openhab.ui/doc/components/oh-icon.md
  bundles/org.openhab.ui/doc/components/oh-image-card.md
  bundles/org.openhab.ui/doc/components/oh-image.md
  bundles/org.openhab.ui/doc/components/oh-input-card.md
  bundles/org.openhab.ui/doc/components/oh-input-item.md
  bundles/org.openhab.ui/doc/components/oh-input.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-knob.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-item.md
  bundles/org.openhab.ui/doc/components/oh-link.md
  bundles/org.openhab.ui/doc/components/oh-list-item.md
  bundles/org.openhab.ui/doc/components/oh-map-circle-marker.md
  bundles/org.openhab.ui/doc/components/oh-map-marker.md
  bundles/org.openhab.ui/doc/components/oh-plan-marker.md
  bundles/org.openhab.ui/doc/components/oh-rollershutter-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider.md
  bundles/org.openhab.ui/doc/components/oh-stepper.md
  bundles/org.openhab.ui/doc/components/oh-time-series.md
  bundles/org.openhab.ui/doc/components/oh-toggle.md
  bundles/org.openhab.ui/doc/components/oh-video.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/actions.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/input.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-button.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-link.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-stepper.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-toggle.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/slide-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/variable-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
Labels: enhancement, main ui

#1554 Fixes to canvas layout display in full screen.
  bundles/org.openhab.ui/doc/components/oh-canvas-layout.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/layout/index.js
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-layout.vue
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
Labels: enhancement, main ui

#1574 Improved sitemap handling in MainUI
  bundles/org.openhab.ui/web/jest.config.js
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/fields/audiosink-field.js
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/dslUtil_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: bug, main ui

#1582 Add context parameter to rule action
  bundles/org.openhab.ui/doc/components/oh-aggregate-series.md
  bundles/org.openhab.ui/doc/components/oh-button.md
  bundles/org.openhab.ui/doc/components/oh-calendar-axis.md
  bundles/org.openhab.ui/doc/components/oh-calendar-series.md
  bundles/org.openhab.ui/doc/components/oh-cell.md
  bundles/org.openhab.ui/doc/components/oh-clock-card.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-cell.md
  bundles/org.openhab.ui/doc/components/oh-data-series.md
  bundles/org.openhab.ui/doc/components/oh-gauge-card.md
  bundles/org.openhab.ui/doc/components/oh-icon.md
  bundles/org.openhab.ui/doc/components/oh-image-card.md
  bundles/org.openhab.ui/doc/components/oh-image.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-item.md
  bundles/org.openhab.ui/doc/components/oh-link.md
  bundles/org.openhab.ui/doc/components/oh-list-item.md
  bundles/org.openhab.ui/doc/components/oh-map-circle-marker.md
  bundles/org.openhab.ui/doc/components/oh-map-marker.md
  bundles/org.openhab.ui/doc/components/oh-plan-marker.md
  bundles/org.openhab.ui/doc/components/oh-rollershutter-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-time-series.md
  bundles/org.openhab.ui/doc/components/oh-video.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/actions.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
Labels: enhancement, main ui

#1578 Normalize channel label before suggesting it as item name
  bundles/org.openhab.ui/web/src/components/thing/channel-list.vue
  bundles/org.openhab.ui/web/src/js/openhab/index.js
  bundles/org.openhab.ui/web/src/js/openhab/utils.js
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-thing.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/generate-textual-definition.js
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
  bundles/org.openhab.ui/web/test/jest/__tests__/utils.test.js
Labels: bug, main ui

#1612 [basicui] Fix setpoint/slider widgets when %unit% is used in state pattern
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SetpointRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SliderRenderer.java
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui, patch
