Repository openhab/openhab-webui, pull requests merged in 2023-11, with the labels that each got.

#2137 `oh-stepper`: Fix NaN shown for Item state with unit & Fix unable to control Item with NaN state
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-stepper.vue
Labels: bug, main ui, regression

#2160 Fix invalid chart period "3M" of sitemaps
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: bug, main ui

#2159 Fix error when actionAnalyzerItems value is a string
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
Labels: bug, main ui

#2031 [webaudio] Allow stopping play
  bundles/org.openhab.ui/web/src/components/sse-events-mixin.js
Labels: enhancement, main ui

#2131 Things: Add copy channel functionality
  bundles/org.openhab.ui/web/src/components/thing/channel-link.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-copy.vue
Labels: enhancement, main ui

#2088 Intergrated Help Features
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/developer/developer-dock.vue
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/help/addon-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/default-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/help-faq-defs.json
  bundles/org.openhab.ui/web/src/components/developer/help/help-qstart-defs.json
  bundles/org.openhab.ui/web/src/components/developer/help/item-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/model-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/page-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/rule-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/thing-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/transform-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/widget-context.vue
  bundles/org.openhab.ui/web/src/js/store/index.js
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
  bundles/org.openhab.ui/web/src/pages/home.vue
  bundles/org.openhab.ui/web/src/pages/home/overview-tab.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/schedule/schedule.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: enhancement, main ui

#2174 [blockly] Add support for getting persistence previous state value as number
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
Labels: enhancement, main ui

#2175 [blockly] Add parse number block
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-math.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2176 [blockly] Add event available
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js
Labels: enhancement, main ui

#2178 Move JSON defs for help features to assets
  bundles/org.openhab.ui/web/src/assets/definitions/help/help-faq-defs.json
  bundles/org.openhab.ui/web/src/assets/definitions/help/help-qstart-defs.json
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
Labels: main ui

#2122 Rules list: Add filtering by (multiple) tags
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
Labels: enhancement, main ui

#1854 [habpanel] Documentation fixes
  bundles/org.openhab.ui.habpanel/doc/habpanel.md
Labels: habpanel ui

#1853 [habpanel] Document scene activation using the selection widget
  bundles/org.openhab.ui.habpanel/doc/habpanel.md
Labels: habpanel ui

#2179 MainUI CONTRIBUTING.md: Mention Vue DevTools & Add FAQ section
  bundles/org.openhab.ui/CONTRIBUTING.md
Labels: main ui

#2138 Developer sidebar: Support searching (in) sitemaps
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: enhancement, main ui

#2117 Adapt network icon to bright and dark themes
  bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/network.svg
Labels: enhancement, iconset

#2116 Adapt movecontrol icon to bright and dark themes
  bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/movecontrol.svg
Labels: enhancement, iconset

#2182 Re-Apply Fix SSE failure toast container not removed
  bundles/org.openhab.ui/web/src/components/connection-health-mixin.js
Labels: bug, main ui, regression

#2150 Addon suggestions
  bundles/org.openhab.ui/web/src/components/addons/addons-section.vue
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui, awaiting other PR

#2180 Fix developer sidebar conceals "Other Apps" panel
  bundles/org.openhab.ui/web/src/pages/home.vue
Labels: bug, main ui

#2189 Persistence edit: Add forecast strategy
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: enhancement, main ui

#2162 [BasicUI] Fix updating of the chart period parameter in URL
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2190 Extend chart periods to 3Y, 5Y and 10Y
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/chart.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart-component.vue
Labels: enhancement, main ui

#2191 Model Item picker: Add button to expand or collapse model
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
Labels: enhancement, main ui

#2156 Update browserslist-db & Remove unused uglifyjs-webpack-plugin
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: main ui, dependencies, javascript

#2187 [BasicUI] Fix dark theme for selection popups
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/_theming.scss
Labels: enhancement, basic ui
