Repository openhab/openhab-webui, pull requests merged in 2023-08, with the labels that each got.

#2000 [blockly] Add Quantity support to round block
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-math.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/utils.js
Labels: enhancement, main ui

#2007 Widget editor: Add note that properties are not evaluated in the editor
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue
Labels: main ui

#2012 [BasicUI] Upgrade frontend-maven-plugin, node and npm to most recent …
  bundles/org.openhab.ui.basic/pom.xml
Labels: basic ui

#2018 [BasicUI] Add a new setting to choose the nb of columns
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/WebAppConfig.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttons.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/colorpicker.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/group.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/input.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/mapview.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/rollerblind.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/selection.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setpoint.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/slider.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/switch.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text_link.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/webview.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: enhancement, basic ui

#2013 [BasicUI] Add support for framework7 icons
  bundles/org.openhab.ui.basic/gulpfile.js
  bundles/org.openhab.ui.basic/package-lock.json
  bundles/org.openhab.ui.basic/package.json
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_framework7.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main.html
  bundles/org.openhab.ui.basic/src/main/resources/web/framework7-icons.css
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: enhancement, basic ui

#2009 Alexa metadata: Add UoM support to use new Item unit symbol property
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/helpers.js
Labels: enhancement, main ui

#2030 Item details: Fix metadata error thrown when opened
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-menu.vue
Labels: bug, main ui

#2024 Fix missing root semantic classes (e.g. Equipment)
  bundles/org.openhab.ui/web/src/js/store/modules/semantics.js
Labels: bug, main ui

#1995 oh-trend: Fix type of trendlineSampling parameter
  bundles/org.openhab.ui/doc/components/oh-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-cell.md
  bundles/org.openhab.ui/doc/components/oh-trend.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/trend.js
Labels: bug, main ui

#1994 Action module wizard: Update texts to mention scenes and scripts
  bundles/org.openhab.ui/web/src/components/rule/action-module-wizard.vue
Labels: enhancement, main ui

#1993 Delay toast on SSE communication failure by one second
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: enhancement, main ui

#2034 Fix add-ons missing from About Details
  bundles/org.openhab.ui/web/src/pages/about.vue
Labels: bug, main ui

#2032 [blockly] Fix timer remove regression
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-timers.js
Labels: bug, main ui
