Repository openhab/openhab-webui, pull requests merged in 2023-09, with the labels that each got.

#2029 Fix missing labels for semantic cards
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/js/store/modules/semantics.js
Labels: bug, main ui

#1985 Developer sidebar: Add search for transformations
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/search-results.vue
Labels: enhancement, main ui

#1997 Redesign settings page & Add doc links
  bundles/org.openhab.ui/web/src/assets/addon-store.js
  bundles/org.openhab.ui/web/src/assets/i18n/common/en.json
  bundles/org.openhab.ui/web/src/assets/i18n/empty-states/en.json
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/add-on-section.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: enhancement, main ui, rebuild

#2022 [BasicUI] Input element: Fix visibility and label/icon color
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2054 Reverts v-if/v-show change from #2029.
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: bug, main ui, regression

#1989 oh-colorpicker: Fix command not sent when state null & style not accepted & cosmetic error on missing defaultColor
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-colorpicker.vue
Labels: bug, main ui

#2051 Add alexa air quality monitor + remote device types
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/devicetypes.js
Labels: enhancement, main ui

#2010 [BasicUI] Add a new header line for image, chart and video elements.
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ImageRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/MapviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/VideoRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/WebviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/chart.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/image.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/mapview.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/video.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/webview.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/_theming.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#1998 [BasicUI] Handle the new parameter "staticIcon"
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttons.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/colorpicker.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/group.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/input.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/mapview.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/rollerblind.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/selection.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setpoint.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/slider.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/switch.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text_link.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2061 Profile page: Only show latest 10 sessions
  bundles/org.openhab.ui/web/src/assets/i18n/common/en.json
  bundles/org.openhab.ui/web/src/pages/profile.vue
Labels: bug, main ui

#2068 Add CO2 measurement badge to location card
  bundles/org.openhab.ui/doc/components/oh-location-card.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/home/index.js
  bundles/org.openhab.ui/web/src/components/cards/glance/location/measurement-badge.vue
  bundles/org.openhab.ui/web/src/components/cards/location-card.vue
Labels: enhancement, main ui

#2064 Update Alexa color temperature supported item types
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/deviceattributes.js
Labels: enhancement, main ui

#2037 [blockly] Allow `item xxx` to be used for `get xxx of item`
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-items.js
Labels: enhancement, main ui

#2053 Fixes/Improvements for sidebar highlighting, settings page & add-on store
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-list-item.vue
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/addons/addon-config.vue
  bundles/org.openhab.ui/web/src/pages/addons/addon-details-sheet.vue
  bundles/org.openhab.ui/web/src/pages/addons/addon-details.vue
  bundles/org.openhab.ui/web/src/pages/addons/addon-store-mixin.js
  bundles/org.openhab.ui/web/src/pages/addons/addons-add.vue
  bundles/org.openhab.ui/web/src/pages/addons/addons-list.vue
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/addon-section.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: bug, main ui

#2074 Add routes for home page tabs
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/home.vue
  bundles/org.openhab.ui/web/src/pages/home/homecards-mixin.js
Labels: enhancement, main ui

#2075 Fix SSE failure toast container not removed
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: bug, main ui

#2073 Change setup wizard icon to choose add-ons to install
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#2079 Fix missing jar add-ons on settings page
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: bug, main ui

#2078 Page edit: Add editing of tags
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
Labels: enhancement, main ui

#2062 [basicui] Number of Columns label
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
Labels: basic ui

#2091 Sitemap editor: Trim spaces from color value
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
Labels: bug, main ui

#2090 Fix decimal formatting for oh-stepper
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-stepper.vue
Labels: bug, main ui

#2087 Items tag: added tags to list, unification of items tag edit
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
  bundles/org.openhab.ui/web/src/components/item/item.vue
  bundles/org.openhab.ui/web/src/components/tags/tag-input.vue
  bundles/org.openhab.ui/web/src/components/tags/tag-mixin.js
  bundles/org.openhab.ui/web/src/components/thing/channel-link.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: enhancement, main ui

#2093 Semantic model: Add options to display and search Item names and tags
  bundles/org.openhab.ui/web/src/components/model/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: enhancement, main ui

#2095 Semantic model: Remove duplicate non-semantic tags in Item component
  bundles/org.openhab.ui/web/src/components/model/item-details.vue
Labels: main ui, regression

#1987 Add error page for initial REST request failure & Abort further load
  bundles/org.openhab.ui/web/src/assets/i18n/common/en.json
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/connection-health-mixin.js
  bundles/org.openhab.ui/web/src/components/reload-mixin.js
  bundles/org.openhab.ui/web/src/pages/about.vue
Labels: enhancement, main ui

#2094 Fix `oh-` components cannot be configured in action modals
  bundles/org.openhab.ui/web/src/components/widgets/modals/modal-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: bug, main ui
