Repository openhab/openhab-webui, pull requests merged in 2023-04, with the labels that each got.

#1819 Thing details: Make code tab read-only if not editable
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: bug, main ui

#1815 Enforce required role when accessing admin or `/profile` routes
  bundles/org.openhab.ui/web/src/js/openhab/auth.js
  bundles/org.openhab.ui/web/src/js/routes.js
Labels: bug, main ui

#1824 Sitemap editor: Support `inputHint` config of Input element
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#1448 Add a transformations menu and editor
  bundles/org.openhab.ui/web/src/assets/definitions/transformations.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/developer/blocks/blocks-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/settings-menu.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: enhancement, main ui

#1732 Developer sidebar: Extend search & Sort search results
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/search-results.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/schedule/schedule.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#1821 Add recommended add-ons to the setup wizard
  bundles/org.openhab.ui/web/src/assets/i18n/setup-wizard/en.json
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#1807 Add a SSE reconnection mechanism
  bundles/org.openhab.ui/web/src/js/openhab/sse.js
Labels: bug, main ui

#1808 Show warning if SSE connection or send command fails
  bundles/org.openhab.ui/web/src/assets/i18n/common/en.json
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: enhancement, main ui

#1729 [basicui] input widget
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/InputRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/input.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/_theming.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#1833 `oh-knob`: Update docs for dotted path and line cap parameters
  bundles/org.openhab.ui/doc/components/oh-knob-card.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-knob.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/knob.js
Labels: main ui

#1835 Developer sidebar: Fix search in case of missing thing label
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: bug, main ui

#1834 [BasicUI] Use more contrasted color buttons in widgets when in dark mode
  bundles/org.openhab.ui.basic/web-src/_theming.scss
Labels: enhancement, basic ui

#1829 [BasicUI] Add the "follow system" theme
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/WebAppConfig.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.ui.basic/web-src/_theming.scss
Labels: enhancement, basic ui

#1838 [BasicUI] Change assumption in case icon value contains only 2 segments
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
Labels: enhancement, basic ui

#1845 Transformations: Various enhancements & fixes
  bundles/org.openhab.ui/web/src/assets/definitions/transformations.js
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: enhancement, main ui

#1852 [mainui] - evaluate service as part of series's chart config
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
Labels: enhancement, main ui

#1818 Add a code tab to the Item editor
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
  bundles/org.openhab.ui/web/src/components/config/editor/hint-items.js
  bundles/org.openhab.ui/web/src/components/config/editor/hint-utils.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: enhancement, main ui

#1865 Use right UID attribute in Thing picker
  bundles/org.openhab.ui/web/src/components/config/controls/thing-picker.vue
Labels: bug, main ui
