Repository openhab/openhab-webui, pull requests merged in 2023-03, with the labels that each got.

#1736 Improvements for Eclipse provisioned add-ons
  bundles/org.openhab.ui/web/src/assets/addon-store.js
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-info-table.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-list-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/addons/addon-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/addons/addons-store.vue
Labels: enhancement, main ui

#1747 Fix undefined in widget expression evaluation
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/expression-tester.vue
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: bug, main ui

#1734 Configuration & iPhone style fixes for the `options` widget action
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: bug, main ui

#1749 [BasicUI] Add missing label/color management for rollershutter items
  bundles/org.openhab.ui.basic/src/main/resources/snippets/rollerblind.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#1751 [basicUI] Support iconcolor for non OH source icons
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttons.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/colorpicker.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/group.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/mapview.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/rollerblind.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/selection.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setpoint.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/slider.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/switch.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text_link.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/webview.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#1754 [BasicUI] OH icon scaling
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: bug, basic ui

#1755 [BasicUI] Remove support for List element
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ListRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/list.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/list_row.html
Labels: bug, basic ui

#1733 [basicui] Support primary and secondary as value for label/value colors
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#1756 Basicui primarysecondary icon
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui, regression

#1763 [BasicUI] Fix primary/secondary color for icon
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
Labels: basic ui

#1764 [BasicUI] Remove reference to sitemap.List
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
Labels: basic ui

#1766 [BasicUI] Change defaults when the icon reference is incomplete
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
Labels: basic ui

#1745 No quotes around chart period parameter in generated sitemap DSL
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
Labels: bug, main ui

#1781 Sitemap editor: Fix attribute value capturing in parser & string value handling in widget detail view
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
Labels: bug, main ui

#1652 [mainui] add visibility to floorplan marker
  bundles/org.openhab.ui/doc/components/oh-plan-marker.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/plan/index.js
  bundles/org.openhab.ui/web/src/components/widgets/plan/oh-plan-marker.vue
Labels: enhancement, main ui

#1765 Fixes WebAudio sink not playing on Safari
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: bug, main ui

#1783 Fix sitemap config boolean attributes
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
Labels: bug, main ui

#1785 Fix channel-details not shown
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-edit.vue
Labels: bug, main ui

#1718 Refactor `oh-knob` component to remove `vue-knob-control` & Lazy load dependencies
  bundles/org.openhab.ui/doc/components/index.md
  bundles/org.openhab.ui/doc/components/oh-knob-card.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-knob.md
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/standard/cards.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/standard/cells.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/knob.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-knob.vue
Labels: enhancement, main ui

#1739 Scene editor: Fix triggers/conditions & Remove enable/disable and status
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
Labels: bug, main ui

#1786 Allow setting gradientDirection for oh-trend component
  bundles/org.openhab.ui/doc/components/oh-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-cell.md
  bundles/org.openhab.ui/doc/components/oh-trend.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/trend.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-trend.vue
Labels: enhancement, main ui

#1788 Use channelType label & description as placeholder for channel details
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-general-settings.vue
Labels: enhancement, main ui

#1740 Update Material icons to 6.7.0 & Remove tff fonts
  bundles/org.openhab.ui/web/src/css/icons.css
  bundles/org.openhab.ui/web/src/fonts/Framework7Icons-Regular.ttf
  bundles/org.openhab.ui/web/src/fonts/MaterialIcons-Regular.ttf
  bundles/org.openhab.ui/web/src/fonts/MaterialIcons-Regular.woff
  bundles/org.openhab.ui/web/src/fonts/MaterialIcons-Regular.woff2
Labels: main ui

#1792 [BasicUI] Consider the correct iconset when reloading the icon
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_oh.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_oh_no_state.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#1793 [BasicUI] Handle new color keyword "itemValue"
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ColorpickerRenderer.java
Labels: enhancement, basic ui

#1802 [webui] Fixes #1775
  bundles/org.openhab.ui/web/src/pages/settings/model/generate-textual-definition.js
Labels: bug, main ui

#1814 Fix text overflow in config-sheet component
  bundles/org.openhab.ui/web/src/components/config/config-sheet.vue
Labels: bug, main ui

#1813 Fix action `options` regression
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
Labels: main ui, regression
