Repository openhab/openhab-webui, pull requests merged in 2023-05, with the labels that each got.

#1849 Fix icons not displayed & not dynamic on all pages
  bundles/org.openhab.ui/doc/components/oh-colorpicker-item.md
  bundles/org.openhab.ui/doc/components/oh-input-item.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-item.md
  bundles/org.openhab.ui/doc/components/oh-list-item.md
  bundles/org.openhab.ui/doc/components/oh-plan-marker.md
  bundles/org.openhab.ui/doc/components/oh-player-item.md
  bundles/org.openhab.ui/doc/components/oh-rollershutter-item.md
  bundles/org.openhab.ui/doc/components/oh-slider-item.md
  bundles/org.openhab.ui/doc/components/oh-stepper-item.md
  bundles/org.openhab.ui/doc/components/oh-toggle-item.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/plan/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/standard/cards.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/standard/listitems.js
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/item.vue
  bundles/org.openhab.ui/web/src/components/model/details-pane.vue
  bundles/org.openhab.ui/web/src/components/model/item-details.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-link.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-list.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/list/default-list-item.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-icon.vue
  bundles/org.openhab.ui/web/src/js/openhab/media.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-thing.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
Labels: bug, main ui

#1843 Sitemap and item config parsing adjustments
  bundles/org.openhab.ui/web/src/assets/items-lexer.nearley
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/css/app.styl
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#1870 [blockly] Support storing timers in shared cache
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-timers.js
Labels: enhancement, main ui

#1871 [blockly] Add new `math_round` block with round up, down and by decimals
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-math.js
Labels: enhancement, main ui

#1876 Developer sidebar: Support search in metadata value and config
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: enhancement, main ui

#1875 `oh-knob` & `oh-stepper`: Add offset functionality
  bundles/org.openhab.ui/doc/components/oh-knob-card.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-knob.md
  bundles/org.openhab.ui/doc/components/oh-stepper-card.md
  bundles/org.openhab.ui/doc/components/oh-stepper-item.md
  bundles/org.openhab.ui/doc/components/oh-stepper.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/knob.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/stepper.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-knob.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-stepper.vue
Labels: enhancement, main ui

#1857 `oh-sipclient`: Various fixes & improvements
  bundles/org.openhab.ui/doc/components/oh-sipclient-card.md
  bundles/org.openhab.ui/doc/components/oh-sipclient.md
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/sipclient.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue
Labels: enhancement, main ui

#1823 [BasicUI] Add more examples of valid/invalid URLs in README
  bundles/org.openhab.ui.basic/README.md
Labels: basic ui

#1885 `foreground-service`: Remove visibility change listener beforeDestroy
  bundles/org.openhab.ui/web/src/components/widgets/widget-foreground-service.js
Labels: main ui, regression

#1884 Fix Things by binding & pages by type not in alphabetical order
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/inbox/inbox-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: bug, main ui

#1889 [bloxkly] Fix picker update detection to allow shadow block conversion
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/fields/date-field.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/fields/item-field.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/fields/thing-field.js
Labels: bug, main ui

#1888 Add blockly dev server start & Document npm run dev
  bundles/org.openhab.ui/CONTRIBUTING.md
  bundles/org.openhab.ui/web/package.json
Labels: main ui

#1826 [cometvisu] make sure that folder paths always end with a slash...
  bundles/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/ManagerSettings.java
  bundles/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/util/FsUtil.java
Labels: bug, cometvisu ui

#1897 [BasicUI] Handle properly state updates to NULL or UNDEF
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setpoint.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#1868 [blockly] Toggle between item name or label
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-items.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/fields/item-field.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#1898 [blockly] Add dictionary loop
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-dicts.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#1899 [blockly] Show toast instead of error when saving / running from code preview
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#1893 `oh-knob`: Fix `releaseOnly` not working
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-knob.vue
Labels: main ui, regression

#1901 Items: Add `unit` metadata for UoM (`Number:`) Items
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/namespaces.js
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-menu.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-unit.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
Labels: enhancement, main ui

#1904 `oh-repeater`: Fix new data requested when css visibility changed
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-repeater.vue
Labels: bug, main ui

#1900 Item & Thing code tabs: Minor fixes
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: bug, main ui

#1894 `oh-slider`: Fix command sent on state update due to rounding
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-slider.vue
Labels: bug, main ui

#1908 Add BasicUI to recommended add-ons
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#1910 Widget editor: Add minus as allowed char of widget uid
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue
Labels: enhancement, main ui
