Repository openhab/openhab-webui, pull requests merged in 2023-06, with the labels that each got.

#1891 Remove "Other Services" section from main settings page
  bundles/org.openhab.ui/web/src/pages/settings/settings-menu.vue
Labels: enhancement, main ui

#1920 `oh-slider` & `oh-knob`: Fix user configured unit (state description) ignored
  bundles/org.openhab.ui/doc/components/oh-slider-card.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-item.md
  bundles/org.openhab.ui/doc/components/oh-slider.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/slider.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-slider.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/slide-mixin.js
Labels: bug, main ui

#1924 `oh-slider` & `oh-knob`: Add option to ignore displayState
  bundles/org.openhab.ui/doc/components/oh-knob-card.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-knob.md
  bundles/org.openhab.ui/doc/components/oh-slider-card.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-item.md
  bundles/org.openhab.ui/doc/components/oh-slider.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/knob.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/slider.js
  bundles/org.openhab.ui/web/src/components/widgets/system/slide-mixin.js
Labels: enhancement, main ui

#1922 [BasicUI] Adjust slider unit handling
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#1916 [HABot] Use SemanticsService to search for label/synonyms of a tag class
  bundles/org.openhab.ui.habot/src/main/java/org/openhab/ui/habot/nlp/internal/SemanticsItemResolver.java
Labels: enhancement, habot ui

#1928 Sitemap parser: Fix negative numbers not allowed for visibility
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
Labels: bug, main ui, regression

#1932 Improvements to the add-on page
  bundles/org.openhab.ui/web/src/components/addons/addon-info-table.vue
  bundles/org.openhab.ui/web/src/pages/settings/addons/addon-details.vue
Labels: enhancement, main ui

#1937 [BasicUI] Set color-scheme for OH icon
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
Labels: enhancement, basic ui

#1917 Add a persistence configuration page
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/addons/addon-config.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/configuration-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/cron-strategy-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/filter-picker.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/filter-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/strategy-picker.vue
Labels: enhancement, main ui

#1925 `oh-sipclient`: Fix audio playback stays active when foreground is left
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue
Labels: bug, main ui

#1936 Items: Fix `unit` metadata not available for UoM groups
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-menu.vue
Labels: bug, main ui

#1882 Dynamically load the list of Semantic tags and store them in Vuex
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/bg.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/ca.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/cs.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/da.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/de.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/el.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/en.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/es.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/fa.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/fi.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/fr.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/he.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/hu.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/it.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/iw.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/lb.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/lv.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/nl.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/no.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/pl.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/pt-BR.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/pt.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/ru.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/sk.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/sl.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/sv.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/uk.json
  bundles/org.openhab.ui/web/src/assets/i18n/semantics/zh.json
  bundles/org.openhab.ui/web/src/assets/semantics.js
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/cards/property-card.vue
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
  bundles/org.openhab.ui/web/src/components/tags/tag-input.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-list.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/cell/default-cell-item.js
  bundles/org.openhab.ui/web/src/components/widgets/standard/default-standalone-item.js
  bundles/org.openhab.ui/web/src/components/widgets/standard/list/default-list-item.js
  bundles/org.openhab.ui/web/src/js/store/index.js
  bundles/org.openhab.ui/web/src/js/store/modules/semantics.js
  bundles/org.openhab.ui/web/src/pages/home/homecards-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/generate-textual-definition.js
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: enhancement, main ui

#1946 Developer sidebar: Support search for Blockly rules/scripts
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: enhancement, main ui

#1947 Developer sidebar: Support search for rule tags
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: enhancement, main ui
