Repository openhab/openhab-webui, pull requests merged in 2023-10, with the labels that each got.

#2085 [BasicUI] Prefer icon over text in buttons (switch element)
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/WebAppConfig.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/button.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: enhancement, basic ui

#2110 [BasicUI] Prefer sitemap label to name in sitemap selection
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main_static.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/sitemaps_list_item.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: enhancement, basic ui

#2112 [BasicUI] Hide header row if label not explicitly set
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ImageRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/MapviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/VideoRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/WebviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/chart.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/image.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2109 Fix `oh-stepper` not working if step is an integer
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-stepper.vue
Labels: bug, main ui, regression

#2041 [blockly] Support Quantity in more math blocks
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-math.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2055 Adds an UI command Item
  bundles/org.openhab.ui/web/src/assets/i18n/theme-switcher/en.json
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/sse-events-mixin.js
  bundles/org.openhab.ui/web/src/components/theme-switcher.vue
Labels: enhancement, main ui

#2107 Things list: Add grouping by location & Display location in list entries
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#2120 Item edit: Dynamically load UoM dimensions
  bundles/org.openhab.ui/web/src/assets/item-types.js
  bundles/org.openhab.ui/web/src/components/config/editor/hint-items.js
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/uom-mixin.js
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
Labels: enhancement, main ui

#2125 Unwrap command Item picker from f7-list-item
  bundles/org.openhab.ui/web/src/assets/i18n/theme-switcher/en.json
  bundles/org.openhab.ui/web/src/components/theme-switcher.vue
Labels: bug, main ui

#2146 Fix oh-clock context in clock card
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-clock-card.vue
Labels: bug, main ui

#2132 Add copy rule functionality
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
Labels: enhancement, main ui

#2020 [BasicUI] Add support for icons based on conditional rules
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_oh.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2145 Sitemap editor: Support AND conditions and icon rules
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/dslUtil_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2135 Fix missing footer element for Item Vue component
  bundles/org.openhab.ui/web/src/components/item/item.vue
Labels: bug, main ui, regression

#2144 Configurable visibility of semantic model cards
  bundles/org.openhab.ui/web/src/components/cards/model-card.vue
  bundles/org.openhab.ui/web/src/pages/home/model-tab.vue
Labels: enhancement, main ui

#2136 Fix color picker not displayed correctly
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-colorpicker.vue
Labels: bug, main ui, regression

#2154 Create aux badge for humidity setpoints similar to temperature badge
  bundles/org.openhab.ui/web/src/components/cards/glance/location/measurement-badge.vue
Labels: enhancement, main ui

#2157 SSE event mixin: Replace RegEx lookbehind assertion with split by string
  bundles/org.openhab.ui/web/.eslintrc.js
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/components/sse-events-mixin.js
Labels: bug, main ui, regression
