Repository openhab/openhab-webui, pull requests merged in 2023-12, with the labels that each got.

#2126 Set unit metadata & state description pattern when creating UoM Item
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
  bundles/org.openhab.ui/web/src/components/item/uom-mixin.js
  bundles/org.openhab.ui/web/src/components/model/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: enhancement, main ui

#2200 Item edit: Fix wording of Item name alert
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: main ui

#2194 Fix alexa item group type parameter support
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/deviceattributes.js
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/devicetypes.js
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-alexa.vue
Labels: bug, main ui

#2083 Rule/script/scene edit: Update tag input & Refactoring
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/components/rule/rule-general-settings.vue
  bundles/org.openhab.ui/web/src/components/tags/tag-input.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-general-settings.vue
Labels: enhancement, main ui

#2184 Items list: Fix searchbar broken after Items list update & Fix search query not stored
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: bug, main ui

#2203 Rule edit: Only save rule if it has changed when opening script editor
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
Labels: bug, main ui

#2212 Help sidebar & Overview page: Respect release type for doc links & Add persistence FAQs
  bundles/org.openhab.ui/web/src/assets/definitions/help/help-faq-defs.json
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
  bundles/org.openhab.ui/web/src/pages/home/overview-tab.vue
Labels: enhancement, main ui

#2210 [blockly] Add block to get hue, saturation and brightness from Color Item
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-color.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2195 [BasicUI] Implement Buttongrid widget
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ButtongridRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttoncell.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttongrid.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttons.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/_theming.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2214 Support time in oh-input widget
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
Labels: enhancement, main ui

#2215 oh-input: Update component docs & Minor fixes
  bundles/org.openhab.ui/doc/components/oh-input-card.md
  bundles/org.openhab.ui/doc/components/oh-input-item.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/input.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
Labels: bug, main ui

#2193 Sitemap Editor: Buttongrid support
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/dslUtil_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/attribute-details.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui, rebuild

#2218 Sitemap editor: Move collapse chevron for toolbar to the left
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2217 Limit add-on settings menu list to bundles
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: bug, main ui

#2220 Update openhab-js tern defs
  bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
Labels: main ui

#2221 Fix unwanted model card back navigation
  bundles/org.openhab.ui/web/src/pages/home.vue
Labels: bug, main ui

#2224 Model page: Add expand/collapse model button
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: enhancement, main ui

#2222 Add panel for voiceSystem metadata
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/namespaces.js
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-voicesystem.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
Labels: enhancement, main ui

#2226 No suggestion for installed add-ons
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: bug, main ui

#2234 [BasicUI] Fix closing h4 tag in sitemap list page
  bundles/org.openhab.ui.basic/src/main/resources/snippets/sitemaps_list.html
Labels: bug, basic ui

#2245 Fix Quickstart-Button shown for non-admin users
  bundles/org.openhab.ui/web/src/pages/home/overview-tab.vue
Labels: bug, main ui

#2229 Add a new settings menu for persistence
  bundles/org.openhab.ui/web/src/assets/i18n/empty-states/en.json
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/addons/addon-config.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-settings.vue
Labels: enhancement, main ui
