Repository openhab/openhab-webui, pull requests merged in 2023-07, with the labels that each got.

#1661 Use cacheable lists when possible
  bundles/org.openhab.ui/web/src/components/config/controls/item-picker.vue
  bundles/org.openhab.ui/web/src/components/config/controls/rule-picker.vue
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
  bundles/org.openhab.ui/web/src/components/config/controls/thing-picker.vue
  bundles/org.openhab.ui/web/src/components/config/controls/triggerchannel-picker.vue
  bundles/org.openhab.ui/web/src/components/config/editor/hint-components.js
  bundles/org.openhab.ui/web/src/components/config/editor/hint-rules.js
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/pages/home/homecards-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
  bundles/org.openhab.ui/web/src/pages/settings/settings-menu.vue
Labels: enhancement, main ui

#1923 [basicui] Use sitemap input hint v2
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/InputRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/input.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/_theming.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#1799 [BasicUI] Use inline SVG for "colorless" SVG icons
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/WebAppConfig.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#1955 Persistence configuration page: Minor enhancements & fixes
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: enhancement, main ui

#1970 Fix masonry configuration failure
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
Labels: bug, main ui

#1971 oh-colorpicker: Add defaultColor option
  bundles/org.openhab.ui/doc/components/oh-colorpicker-card.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-cell.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-item.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/colorpicker.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-colorpicker.vue
Labels: enhancement, main ui

#1984 Developer sidebar: Fix Thing pinning fails
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: bug, main ui

#1988 Persistence editor: Remove checks on save as not required anymore
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: enhancement, main ui

#1986 Semantic tags: Fix missing translations in case of missing label
  bundles/org.openhab.ui/web/src/js/store/modules/semantics.js
Labels: bug, main ui

#1983 Use dynamic links for docs
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-ga.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-homekit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
Labels: enhancement, main ui

#1992 Blockly: Support String/Number on eventcontext state/command
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js
Labels: bug, enhancement, main ui, patch
