Repository openhab/openhab-webui, pull requests merged in 2023-02, with the labels that each got.

#1688 [habpanel] Use commandDescription instead of stateDescription for selection list
  bundles/org.openhab.ui.habpanel/web/app/widgets/selection/selection.widget.js
Labels: bug, habpanel ui

#1683 [MainUI] Fixes & Enhancements for channel add & edit pages
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-general-settings.vue
Labels: bug, main ui

#1684 Fix add-on configuration
  bundles/org.openhab.ui/web/src/pages/settings/addons/addon-config.vue
Labels: bug, main ui

#1681 add doc link to state/commandDescription edit form
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-itemdescription.vue
Labels: enhancement, main ui

#1700 Validate Widget UID & page ID on creation
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pagedesigner-mixin.js
Labels: enhancement, main ui

#1699 Improve Item name validation error message & Add unchangeable note on Item creation
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
Labels: enhancement, main ui

#1696 Display `undefined` correctly in widget expressions
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: bug, main ui

#1695 Improve SIP Client component docs
  bundles/org.openhab.ui/doc/components/oh-map-page.md
  bundles/org.openhab.ui/doc/components/oh-sipclient-card.md
  bundles/org.openhab.ui/doc/components/oh-sipclient.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/sipclient.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue
Labels: enhancement, main ui

#1670 [MainUI] Fix redirection for reverse proxy with authentication not working
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: enhancement, main ui

#1703 Add new capabilities to oh-knob component using vue-round-slider
  bundles/org.openhab.ui/doc/components/images/oh-knob/header.png
  bundles/org.openhab.ui/doc/components/oh-gauge-card.md
  bundles/org.openhab.ui/doc/components/oh-gauge.md
  bundles/org.openhab.ui/doc/components/oh-knob-card.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-knob.md
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/standard/cards.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/knob.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-knob.vue
Labels: enhancement, main ui

#1712 [basicui] Remove Roboto font as unused by the app
  bundles/org.openhab.ui.basic/gulpfile.js
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main_static.html
  bundles/org.openhab.ui.basic/src/main/resources/web/roboto.css
Labels: bug, basic ui

#1662 Add a Scene settings menu entry and editor
  bundles/org.openhab.ui/doc/components/oh-aggregate-series.md
  bundles/org.openhab.ui/doc/components/oh-button.md
  bundles/org.openhab.ui/doc/components/oh-calendar-axis.md
  bundles/org.openhab.ui/doc/components/oh-calendar-series.md
  bundles/org.openhab.ui/doc/components/oh-cell.md
  bundles/org.openhab.ui/doc/components/oh-clock-card.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-cell.md
  bundles/org.openhab.ui/doc/components/oh-data-series.md
  bundles/org.openhab.ui/doc/components/oh-gauge-card.md
  bundles/org.openhab.ui/doc/components/oh-icon.md
  bundles/org.openhab.ui/doc/components/oh-image-card.md
  bundles/org.openhab.ui/doc/components/oh-image.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-item.md
  bundles/org.openhab.ui/doc/components/oh-link.md
  bundles/org.openhab.ui/doc/components/oh-list-item.md
  bundles/org.openhab.ui/doc/components/oh-map-circle-marker.md
  bundles/org.openhab.ui/doc/components/oh-map-marker.md
  bundles/org.openhab.ui/doc/components/oh-plan-marker.md
  bundles/org.openhab.ui/doc/components/oh-rollershutter-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-time-series.md
  bundles/org.openhab.ui/doc/components/oh-video.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/actions.js
  bundles/org.openhab.ui/web/src/assets/i18n/empty-states/en.json
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/config/controls/rule-picker.vue
  bundles/org.openhab.ui/web/src/components/config/controls/thing-picker.vue
  bundles/org.openhab.ui/web/src/components/config/editor/hint-rules.js
  bundles/org.openhab.ui/web/src/components/config/editor/yaml-utils.js
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-configure-item-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/settings-menu.vue
Labels: enhancement, main ui

#1723 [Blockly] Add workspace search
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/blockly-editor.vue
Labels: enhancement, main ui

#1726 Add step parameter to oh-input
  bundles/org.openhab.ui/doc/components/oh-input-card.md
  bundles/org.openhab.ui/doc/components/oh-input-item.md
  bundles/org.openhab.ui/doc/components/oh-input.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/input.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
Labels: enhancement, main ui

#1720 Save changed rule/scene on runNow & Fix keyboard shortcuts in scene editor
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#1656 Z-Wave map: show only current network, link fixes
  bundles/org.openhab.ui/web/src/components/thing/zwave/zwave-network.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/zwave/zwave-network-popup.vue
Labels: bug, main ui

#1727 Handle NOT_YET_READY in thing status
  bundles/org.openhab.ui/web/src/assets/i18n/thing-status/en.json
Labels: bug, main ui

#1706 [basicui] Add support for iconify and Google material icons
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/WebAppConfig.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ColorpickerRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/MapviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SetpointRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/WebviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttons.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/colorpicker.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/group.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_iconify.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_material.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_oh.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_oh_no_state.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/mapview.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/rollerblind.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/selection.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setpoint.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/slider.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/switch.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/text_link.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/webview.html
  bundles/org.openhab.ui.basic/src/main/resources/web/iconify/iconify-icon.min.js
  bundles/org.openhab.ui.basic/src/main/resources/web/material-icons.css
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#1735 Support configuring Input element for sitemap model
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui
