Repository openhab/openhab-webui, pull requests merged in 2024-07, with the labels that each got.

#2638 Do not request icon with state for Image Items
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/item.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-link.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: bug, main ui

#2640 Developer sidebar: Fix script and scene "unpin all" links
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: bug, main ui

#2642 Update openhab-js tern defs
  bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
Labels: main ui

#2643 Fix a typo in orphanlinks page
  bundles/org.openhab.ui/web/src/pages/settings/health/health-orphanlinks.vue
Labels: main ui

#2649 [BasicUI] Fix iconify parameter description
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
Labels: bug, basic ui

#2652 Health menu: Remove sidebar and settings entry, instead use FAB
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/pages/settings/health/health-orphanlinks.vue
  bundles/org.openhab.ui/web/src/pages/settings/health/health-overview.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: main ui

#2647 Make tabbed pages routable
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
Labels: enhancement, main ui

#2655 Fix code editor overflow in sitemap editor
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
Labels: bug, main ui, patch

#2656 Page editors: Encapsulate CSS to avoid polluting global CSS
  bundles/org.openhab.ui/web/src/pages/settings/pages/chart/chart-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/home/home-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/map/map-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/plan/plan-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/tabs/tabs-edit.vue
Labels: bug, main ui, patch

#2657 Fix sidebar openHAB logo href to avoid repeated navigation to home page
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: bug, main ui

#2648 oh-sipclient: Add call status Item to report call status to server
  bundles/org.openhab.ui/doc/components/oh-sipclient-card.md
  bundles/org.openhab.ui/doc/components/oh-sipclient.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/sipclient.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue
Labels: enhancement, main ui

#2662 oh-context: Fix rendering failure when not in edit mode
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-context.vue
Labels: bug, main ui

#2663 Canvas layout page: Hide empty background image element to remove white border
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-layout.vue
Labels: bug, main ui

#2666 oh-sipclient: Regenerate component docs
  bundles/org.openhab.ui/doc/components/oh-sipclient-card.md
  bundles/org.openhab.ui/doc/components/oh-sipclient.md
Labels: main ui

#2673 Overview page: Fix `defineVars` is not working
  bundles/org.openhab.ui/web/src/pages/home/overview-tab.vue
Labels: bug, main ui

#2677 Charts: Fix issues with charts not displaying on iOS >= 17.4
  bundles/org.openhab.ui/web/src/components/widgets/chart/oh-chart-page.vue
  bundles/org.openhab.ui/web/src/pages/analyzer/analyzer.vue
Labels: bug, main ui

#2678 Fix 404s for overview page, semantic model tabs and add-on store
  bundles/org.openhab.ui/src/main/java/org/openhab/ui/internal/UIErrorPageServlet.java
Labels: bug, main ui

#2661 [BasicUI] Add a translatable title to the settings page
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
Labels: enhancement, basic ui

#2672 [blockly] Add new sophisticated notification blocks
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-notifications.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2686 [blockly] Fixes for notification block code generation
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-notifications.js
Labels: main ui

#2688 [blockly] Fix code generation for Thing object on Thing status block
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-things.js
Labels: bug, main ui, patch

#2689 Link add: Fix create item fails for trigger channels
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: bug, main ui, patch

#2690 Link add: Support linking Number channel to Switch Item with profile
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: bug, main ui
