Repository openhab/openhab-webui, pull requests merged in 2024-10, with the labels that each got.

#2780 oh-canvas-layout: Allow overriding style
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-layout.vue
Labels: bug, main ui

#2781 Refactor card widgets to use a shared base component
  bundles/org.openhab.ui/doc/components/images/oh-card/example.png
  bundles/org.openhab.ui/doc/components/index.md
  bundles/org.openhab.ui/doc/components/oh-canvas-layout.md
  bundles/org.openhab.ui/doc/components/oh-card.md
  bundles/org.openhab.ui/doc/components/oh-slider-card.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-item.md
  bundles/org.openhab.ui/doc/components/oh-slider.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/helpers.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/layout/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/standard/cards.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/slider.js
  bundles/org.openhab.ui/web/src/components/widgets/generic-widget-component.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/index.js
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-clock-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-colorpicker-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-gauge-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-image-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-input-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-knob-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-label-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-list-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-player-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-rollershutter-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-sipclient-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-slider-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-stepper-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-swiper-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-toggle-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-video-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-webframe-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-card-footer.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
Labels: enhancement, main ui

#2783 Fix meta tag apple-mobile-web-app-capable deprecation warning
  bundles/org.openhab.ui/web/src/index.html
Labels: main ui

#2786 Thing details: Fix config action Thing config modification
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: main ui

#2791 Change the default navbar style for non-desktop to simple navbar
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/theme-switcher.vue
  bundles/org.openhab.ui/web/src/pages/home.vue
Labels: enhancement, main ui

#2792 Item details: Show group function for group Items if defined
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
Labels: enhancement, main ui

#2794 Fix oh-gauge-card action regression & Improve oh-card docs
  bundles/org.openhab.ui/doc/components/index.md
  bundles/org.openhab.ui/doc/components/oh-card.md
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-gauge-card.vue
Labels: main ui, regression

#2795 Fix oh-image-card action regression
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-image-card.vue
Labels: main ui, regression

#2755 Sitemap editor: Add Buttongrid Button support
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/dslUtil_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2799 Revert "Change the default navbar style for non-desktop to simple navbar"
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/theme-switcher.vue
  bundles/org.openhab.ui/web/src/pages/home.vue
Labels: main ui

#2801 Fix safe area styling issues with card and card contents
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-card.vue
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: bug, main ui

#2802 Settings pages: Fix double scrollbars by hiding y-overflow in block-narrow
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: bug, main ui

#2803 Fix style regressions from #2801
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-card.vue
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: bug, main ui, regression

#2804 Remove unnecessary !important from block style fixes inside f7-card
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: bug, main ui, regression

#2805 Charts: Enable boundary and itemState persistence query params by default
  bundles/org.openhab.ui/doc/components/oh-aggregate-series.md
  bundles/org.openhab.ui/doc/components/oh-calendar-series.md
  bundles/org.openhab.ui/doc/components/oh-time-series.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/index.js
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/chart/series/oh-aggregate-series.js
Labels: enhancement, main ui

#2807 oh-cell: Fix headerBadgeColor
  bundles/org.openhab.ui/web/src/components/widgets/standard/cell/oh-cell.vue
Labels: bug, main ui

#2800 Home page: Add options to set simple navbar/standard background the default on mobile/desktop
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/home/index.js
  bundles/org.openhab.ui/web/src/assets/i18n/theme-switcher/en.json
  bundles/org.openhab.ui/web/src/components/theme-switcher.vue
  bundles/org.openhab.ui/web/src/pages/home.vue
Labels: enhancement, main ui

#2820 Config parameter: Add unit to param description when entering UoM values
  bundles/org.openhab.ui/web/src/components/config/config-parameter.vue
Labels: enhancement, main ui

#2818 Thing page: Support invoking Thing actions & Viewing their output
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-action-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: enhancement, main ui

#2823 Rules list: Store search query when leaving page/reloading & Improve code
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
Labels: enhancement, main ui

#2824 Items list: Add note that states not updated in real-time & Code improvement
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: enhancement, main ui

#2827 Search bars: Remember search query & Automatically focus on desktop
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/schedule/schedule.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#2826 Items & Rules list: Minor style & code improvements
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
Labels: main ui

#2828 Improve injection of build info into the UI
  bundles/org.openhab.ui/web/build/build.js
  bundles/org.openhab.ui/web/build/generate-build-info.mjs
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/.gitignore
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/js/store/index.js
Labels: main ui

#2216 Addons store: Use swiper for addon cards on mobile & Reduce size of addon card on desktop
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
  bundles/org.openhab.ui/web/src/components/addons/addons-section.vue
  bundles/org.openhab.ui/web/src/components/addons/addons-swiper.vue
Labels: enhancement, main ui

#2833 Addons store: Multiple styling improvements
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
  bundles/org.openhab.ui/web/src/components/addons/addons-section.vue
  bundles/org.openhab.ui/web/src/components/addons/addons-swiper.vue
Labels: main ui

#2834 Thing actions: Sort by label, Show description, Hide unsupported actions
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-action-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: main ui

#2837 Fix flickering of list pages when updating
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/schedule/schedule.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: bug, main ui

#2839 Thing actions: Hide if no actions available & Merge with UI actions
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: main ui

#2840 Thing action popup: Multiple improvements
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-action-popup.vue
Labels: main ui

#2848 Config param time & datetime: Add support for seconds
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-datetime.vue
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-time.vue
Labels: enhancement, main ui
