Repository openhab/openhab-webui, pull requests merged in 2024-09, with the labels that each got.

#2741 CSP: Allow embedding any source
  bundles/org.openhab.ui/web/src/index.html
Labels: bug, main ui, regression

#2740 [blockly] Make HTTP block method name dropdown labels less technical
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-http.js
Labels: enhancement, main ui

#2751 Home edit: Fix model tab settings not editable
  bundles/org.openhab.ui/web/src/pages/settings/pages/home/home-edit.vue
Labels: bug, main ui

#2753 Developer sidebar: Show error when trying to run unititialized rule
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: bug, main ui

#2754 Rules/Scenes/Scripts: Gray out run now button if uninitialized
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#2742 [blockly] Small improvements to blocks
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-timers.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/index.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2752 State description metadata: Allow to select transformations from list
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-itemdescription.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
Labels: enhancement, main ui

#2720 Sitemap editor: Validation improvements
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/config/controls/persistence-picker.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2732 [blockly] Add persistence median methods
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
Labels: enhancement, main ui

#2743 [blockly] Remove Nashorn support & Check for required automation add-on in script edit
  bundles/org.openhab.ui/web/src/assets/definitions/automation-languages.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-audio.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-color.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-dateoffsets.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-dicts.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-ephemeris.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-eventbus.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-http.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-items.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-list.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-logging.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-logic.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-math.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-metadata.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-notifications.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-text.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-things.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-timers.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-uom.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-valuestorage.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/utils.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
  bundles/org.openhab.ui/web/src/components/rule/action-module-wizard.vue
  bundles/org.openhab.ui/web/src/components/rule/condition-module-wizard.vue
  bundles/org.openhab.ui/web/src/components/rule/module-wizard-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-general-settings.vue
Labels: enhancement, main ui

#2758 Fix dirty indicator blocks subtitles
  bundles/org.openhab.ui/web/src/pages/developer/blocks/blocks-edit.vue
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/dirty-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/chart/chart-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/home/home-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/map/map-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/plan/plan-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/tabs/tabs-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
Labels: bug, main ui, regression

#2760 Script editor: Extend mode translation for more automation languages
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
Labels: enhancement, main ui

#2761 Script & Transformation editor: Add links to the language reference docs
  bundles/org.openhab.ui/CONTRIBUTING.md
  bundles/org.openhab.ui/web/src/assets/automation-languages.js
  bundles/org.openhab.ui/web/src/assets/transformations.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
Labels: enhancement, main ui

#2746 [BasicUI] Fix character encoding of returned page
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/servlet/ManifestServlet.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/servlet/WebAppServlet.java
Labels: bug, basic ui

#2764 [BasicUI] Hide header row for MJPEG video when visibility is disabled
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/VideoRenderer.java
Labels: bug, basic ui

#2771 Thing add page: Add support for optional scan input
  bundles/org.openhab.ui/web/src/pages/settings/things/add/choose-thing-type.vue
Labels: enhancement, main ui

#2772 Persistence edit: Fix wrong config parameter type definitions
  bundles/org.openhab.ui/web/src/assets/definitions/persistence.js
Labels: bug, main ui

#2773 Config sheet: Properly handle null as configuration value
  bundles/org.openhab.ui/web/src/components/config/config-sheet.vue
Labels: bug, main ui

#2774 Z-Wave network map: Fix ECharts deprecation warnings
  bundles/org.openhab.ui/web/src/components/thing/zwave/zwave-network.vue
Labels: enhancement, main ui

#2776 Thing add page: Fix header styling for input field
  bundles/org.openhab.ui/web/src/pages/settings/things/add/choose-thing-type.vue
Labels: main ui

#2777 oh-rollershutter: Use displayState if available & Improve styling
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-rollershutter-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-rollershutter.vue
Labels: bug, main ui

#2779 System & Add-on settings: Add dirty indicator & Improve dirty handling
  bundles/org.openhab.ui/web/src/pages/addons/addon-config.vue
  bundles/org.openhab.ui/web/src/pages/settings/services/service-settings.vue
Labels: enhancement, main ui
