Repository openhab/openhab-webui, pull requests merged in 2024-08, with the labels that each got.

#2693 Clean-up unused login/logout code in app.vue
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/auth-mixin.js
  bundles/org.openhab.ui/web/src/pages/profile.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
Labels: enhancement, main ui

#2694 SSE state tracking: Reduce logging
  bundles/org.openhab.ui/web/src/js/store/modules/states.js
Labels: enhancement, main ui

#2687 Add a dirty indicator on the title bar
  bundles/org.openhab.ui/web/src/pages/developer/blocks/blocks-edit.vue
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/dirty-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/chart/chart-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/home/home-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/map/map-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/plan/plan-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/tabs/tabs-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
Labels: enhancement, main ui

#2695 Page designers: Fix dirty handling for code tab
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pagedesigner-mixin.js
Labels: bug, main ui

#2698 [BasicUI] Revert uppercasing exponent
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2697 [BasicUI] Make button text not uppercased
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: enhancement, basic ui

#2700 [BasicUI] Fix frame title's left padding in condensed tablet layout
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: bug, basic ui

#2699 [BasicUI] Remove reading of frequency parameter of colorpicker element
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ColorpickerRenderer.java
Labels: basic ui

#2705 Sitemap editor: Remove sendFrequency parameter
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
Labels: enhancement, main ui

#2691 Update HomeKit metadata definitions
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/homekit.js
Labels: enhancement, main ui

#2584 Allow model cards and model tabs outside of homepage
  bundles/org.openhab.ui/doc/components/index.md
  bundles/org.openhab.ui/doc/components/oh-equipment-card.md
  bundles/org.openhab.ui/doc/components/oh-location-card.md
  bundles/org.openhab.ui/doc/components/oh-property-card.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/home/index.js
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/cards/equipment-card.vue
  bundles/org.openhab.ui/web/src/components/cards/location-card.vue
  bundles/org.openhab.ui/web/src/components/cards/property-card.vue
  bundles/org.openhab.ui/web/src/components/sse-events-mixin.js
  bundles/org.openhab.ui/web/src/components/tabs/equipment-tab.vue
  bundles/org.openhab.ui/web/src/components/tabs/locations-tab.vue
  bundles/org.openhab.ui/web/src/components/tabs/properties-tab.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/index.js
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-equipment-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-location-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-property-card.vue
  bundles/org.openhab.ui/web/src/js/store/index.js
  bundles/org.openhab.ui/web/src/js/store/modules/model.js
  bundles/org.openhab.ui/web/src/pages/home.vue
  bundles/org.openhab.ui/web/src/pages/home/homecards-mixin.js
  bundles/org.openhab.ui/web/src/pages/home/model-tab.vue
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/home/home-edit.vue
Labels: enhancement, main ui

#2706 Charts: Force re-render on device orientation change
  bundles/org.openhab.ui/web/src/components/widgets/chart/oh-chart-page.vue
Labels: bug, main ui

#2707 Upgrade build dependencies & Apply new ESLint config
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/libraries.js
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/cards/glance/location/status-badge.vue
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-script.vue
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-homekit.vue
  bundles/org.openhab.ui/web/src/components/model/link-details.vue
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-group.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-link.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-list.vue
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/component-id.js
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-layer.vue
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-layout.vue
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-grid-layout.vue
  bundles/org.openhab.ui/web/src/components/widgets/modals/modal-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/variable-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-expression-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
  bundles/org.openhab.ui/web/src/js/compatibility.js
  bundles/org.openhab.ui/web/src/js/i18n.js
  bundles/org.openhab.ui/web/src/js/openhab/api.js
  bundles/org.openhab.ui/web/src/js/openhab/auth.js
  bundles/org.openhab.ui/web/src/js/store/modules/model.js
  bundles/org.openhab.ui/web/src/js/store/modules/states.js
  bundles/org.openhab.ui/web/src/pages/analyzer/analyzer.vue
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
  bundles/org.openhab.ui/web/src/pages/settings/dirty-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/parser/items-add-from-textual-definition.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-template.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/generate-textual-definition.js
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/map/map-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: main ui

#2708 Upgrade @jsep/template-plugin, dayjs, echarts, qrcode & yaml
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: main ui

#2709 Upgrade dependencies with security vulnerabilities
  bundles/org.openhab.ui/web/package-lock.json
Labels: main ui, dependencies

#2710 Charts: Improve forced re-render code to keep settings and loaded data
  bundles/org.openhab.ui/web/src/components/widgets/chart/oh-chart-page.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart-component.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart.vue
Labels: main ui

#2711 Widget actions: Add a HTTP action to perform HTTP requests
  bundles/org.openhab.ui/doc/components/oh-aggregate-series.md
  bundles/org.openhab.ui/doc/components/oh-button.md
  bundles/org.openhab.ui/doc/components/oh-calendar-axis.md
  bundles/org.openhab.ui/doc/components/oh-calendar-series.md
  bundles/org.openhab.ui/doc/components/oh-cell.md
  bundles/org.openhab.ui/doc/components/oh-clock-card.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-cell.md
  bundles/org.openhab.ui/doc/components/oh-data-series.md
  bundles/org.openhab.ui/doc/components/oh-gauge-card.md
  bundles/org.openhab.ui/doc/components/oh-icon.md
  bundles/org.openhab.ui/doc/components/oh-image-card.md
  bundles/org.openhab.ui/doc/components/oh-image.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-item.md
  bundles/org.openhab.ui/doc/components/oh-link.md
  bundles/org.openhab.ui/doc/components/oh-list-item.md
  bundles/org.openhab.ui/doc/components/oh-map-circle-marker.md
  bundles/org.openhab.ui/doc/components/oh-map-marker.md
  bundles/org.openhab.ui/doc/components/oh-plan-marker.md
  bundles/org.openhab.ui/doc/components/oh-rollershutter-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-time-series.md
  bundles/org.openhab.ui/doc/components/oh-video.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/actions.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
Labels: enhancement, main ui

#2713 Revert "Bump braces and gulp in /bundles/org.openhab.ui.basic"
  bundles/org.openhab.ui.basic/package-lock.json
  bundles/org.openhab.ui.basic/package.json
Labels: basic ui, regression

#2714 Main UI: Improve Content-Security-Policy
  bundles/org.openhab.ui/web/src/index.html
Labels: enhancement, main ui

#2716 Main UI: Allow use of eval() in CSP
  bundles/org.openhab.ui/web/src/index.html
Labels: main ui, regression

#2685 [BasicUI] input widget, support html escape characters in input
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/InputRenderer.java
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2607 [blockly] HTTP block enhancements
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-http.js
Labels: enhancement, main ui

#2721 HomeKit metadata: Mark Thermostat.CurrentHeatingCoolingMode as optional
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/homekit.js
Labels: enhancement, main ui

#2703 [BasicUI] Add build date to resource requests
  bundles/org.openhab.ui.basic/.gitignore
  bundles/org.openhab.ui.basic/gulpfile.js
  bundles/org.openhab.ui.basic/package-lock.json
  bundles/org.openhab.ui.basic/package.json
  bundles/org.openhab.ui.basic/snippets-src/button.html
  bundles/org.openhab.ui.basic/snippets-src/button_element.html
  bundles/org.openhab.ui.basic/snippets-src/buttoncell.html
  bundles/org.openhab.ui.basic/snippets-src/buttongrid.html
  bundles/org.openhab.ui.basic/snippets-src/buttons.html
  bundles/org.openhab.ui.basic/snippets-src/chart.html
  bundles/org.openhab.ui.basic/snippets-src/colorpicker.html
  bundles/org.openhab.ui.basic/snippets-src/frame.html
  bundles/org.openhab.ui.basic/snippets-src/group.html
  bundles/org.openhab.ui.basic/snippets-src/header_row.html
  bundles/org.openhab.ui.basic/snippets-src/icon_framework7.html
  bundles/org.openhab.ui.basic/snippets-src/icon_iconify.html
  bundles/org.openhab.ui.basic/snippets-src/icon_material.html
  bundles/org.openhab.ui.basic/snippets-src/icon_none.html
  bundles/org.openhab.ui.basic/snippets-src/icon_oh.html
  bundles/org.openhab.ui.basic/snippets-src/icon_oh_no_state.html
  bundles/org.openhab.ui.basic/snippets-src/image.html
  bundles/org.openhab.ui.basic/snippets-src/image_link.html
  bundles/org.openhab.ui.basic/snippets-src/input.html
  bundles/org.openhab.ui.basic/snippets-src/layer.html
  bundles/org.openhab.ui.basic/snippets-src/main.html
  bundles/org.openhab.ui.basic/snippets-src/main_static.html
  bundles/org.openhab.ui.basic/snippets-src/manifest.json
  bundles/org.openhab.ui.basic/snippets-src/mapview.html
  bundles/org.openhab.ui.basic/snippets-src/rollerblind.html
  bundles/org.openhab.ui.basic/snippets-src/selection.html
  bundles/org.openhab.ui.basic/snippets-src/selection_row.html
  bundles/org.openhab.ui.basic/snippets-src/setpoint.html
  bundles/org.openhab.ui.basic/snippets-src/setting_buttons.html
  bundles/org.openhab.ui.basic/snippets-src/setting_selection.html
  bundles/org.openhab.ui.basic/snippets-src/setting_switch.html
  bundles/org.openhab.ui.basic/snippets-src/sitemaps_list.html
  bundles/org.openhab.ui.basic/snippets-src/sitemaps_list_empty.html
  bundles/org.openhab.ui.basic/snippets-src/sitemaps_list_item.html
  bundles/org.openhab.ui.basic/snippets-src/slider.html
  bundles/org.openhab.ui.basic/snippets-src/switch.html
  bundles/org.openhab.ui.basic/snippets-src/text.html
  bundles/org.openhab.ui.basic/snippets-src/text_link.html
  bundles/org.openhab.ui.basic/snippets-src/video.html
  bundles/org.openhab.ui.basic/snippets-src/webview.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/readme.txt
Labels: enhancement, basic ui

#2719 [cometvisu] fix path check regressions
  bundles/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/servlet/CometVisuServlet.java
Labels: bug, cometvisu ui

#2724 [BasicUI] Upgrade Material Icons
  bundles/org.openhab.ui.basic/package-lock.json
  bundles/org.openhab.ui.basic/package.json
Labels: basic ui

#2731 Developer sidebar: Focus on search when opened
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: enhancement, main ui

#2734 Items: Add MEDIAN group function
  bundles/org.openhab.ui/web/src/assets/item-types.js
  bundles/org.openhab.ui/web/src/assets/items-lexer.nearley
Labels: enhancement, main ui

#2722 [BasicUI] Upgrade node/npm/gulp/node-sass tools
  bundles/org.openhab.ui.basic/gulpfile.js
  bundles/org.openhab.ui.basic/package-lock.json
  bundles/org.openhab.ui.basic/package.json
  bundles/org.openhab.ui.basic/pom.xml
Labels: basic ui, dependencies

#2738 Upgrade webpack from 5.93.0 to 5.94.0
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: main ui, dependencies
