Repository openhab/openhab-webui, pull requests merged in 2024-05, with the labels that each got.

#2431 Setup wizard: Add separate step for persistence
  bundles/org.openhab.ui/web/src/assets/i18n/setup-wizard/en.json
  bundles/org.openhab.ui/web/src/components/addons/addons-setup-wizard.vue
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#2556 Setup wizard: Refactor add-on selection & Add descriptions for JS Scripting & Astro
  bundles/org.openhab.ui/web/src/assets/i18n/setup-wizard/en.json
  bundles/org.openhab.ui/web/src/components/addons/addons-setup-wizard.vue
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#2557 [BasicUI] Fix build after a method renaming in core framework
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/servlet/WebAppServlet.java
Labels: basic ui

#2558 Setup wizard: Fix server-set region and location not shown on later wizard launch
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: bug, main ui

#2563 Update openhab-js tern defs
  bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
Labels: enhancement, main ui

#2536 [BasicUI] Implement press & release button
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ButtongridRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/button.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2553 Sitemap editor: Add press release button support
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/dslUtil_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2565 Setup wizard: Add primary IP config
  bundles/org.openhab.ui/web/src/assets/i18n/setup-wizard/en.json
  bundles/org.openhab.ui/web/src/components/addons/addons-setup-wizard.vue
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#2567 Item parser: Add missing group item aggregation functions
  bundles/org.openhab.ui/web/src/assets/items-lexer.nearley
Labels: bug, main ui

#2564 [blockly] Adjust persistence blocks to breaking changes
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
Labels: enhancement, main ui

#2572 [BasicUI] Remove a call to window.console
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: basic ui

#2575 [blockly] Add timer context
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-timers.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2568 Setup Wizard: improve suggestions refresh on network change
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#2578 [BasicUI] Remove a useless call to function reloadIcon (slider widget)
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: basic ui

#2573 [BasicUI] New Button element as child of Buttongrid
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ButtongridRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/button.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/button_element.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2579 [BasicUI] Switch with buttons: value displayed if pattern on widget
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
Labels: enhancement, basic ui

#2581 [blockly] Add typed vars
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-things.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-uom.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2580 [BasicUI] Switch between several Button elements at a place in the grid
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ButtongridRenderer.java
Labels: enhancement, basic ui

#2547 Upgrade Karaf from 4.4.5 to 4.4.6
  bundles/org.openhab.ui.cometvisu/pom.xml
  pom.xml
Labels: awaiting other PR

#2588 [blockly] Fix Thing "is enabled" code generation
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-things.js
Labels: bug, main ui

#2591 Tabbed pages: Show config in code tab & Enable expressions for title and icon
  bundles/org.openhab.ui/web/src/components/widgets/widget-expression-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/tabs/tabs-edit.vue
Labels: enhancement, main ui

#2592 Tabbed pages: Add optional badges and badge color to tabbar
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/tabs/index.js
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
Labels: enhancement, main ui

#2582 Add-on store: Add connection and country filter
  bundles/org.openhab.ui/web/src/assets/addon-store.js
  bundles/org.openhab.ui/web/src/components/addons/addon-info-table.vue
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: enhancement, main ui

#2105 Add a "Add from template" page for the semantic model
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-template.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: enhancement, main ui
