Repository openhab/openhab-webui, pull requests merged in 2024-03, with the labels that each got.

#2312 Provide meaningful list of units in item form
  bundles/org.openhab.ui/web/src/assets/units.js
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
  bundles/org.openhab.ui/web/src/components/item/uom-mixin.js
  bundles/org.openhab.ui/web/src/components/thing/channel-list.vue
  bundles/org.openhab.ui/web/src/js/store/index.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: enhancement, main ui

#2438 Developer dock: Fix styling issue when lazy loading component
  bundles/org.openhab.ui/web/src/components/developer/developer-dock.vue
Labels: main ui, regression

#2440 Add-on logo: Fix jdbc logos not loading & list-item logo distorted
  bundles/org.openhab.ui/web/src/components/addons/addon-list-item.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-logo.vue
Labels: bug, main ui

#2441 Widget expressions: Add `#` as a shorthand for item.numericState
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: enhancement, main ui

#2410 Show lock icon in the item details members list
  bundles/org.openhab.ui/web/src/components/item/group-members.vue
  bundles/org.openhab.ui/web/src/components/item/item.vue
Labels: enhancement, main ui

#2243 [BasicUI] Move most of app settings to per-device (browser) settings
  bundles/org.openhab.ui.basic/.gitignore
  bundles/org.openhab.ui.basic/gulpfile.js
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/WebAppConfig.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ButtongridRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/servlet/WebAppServlet.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.ui.basic/src/main/resources/snippets/button.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/main_static.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setting_buttons.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setting_selection.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/setting_switch.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/_theming.scss
  bundles/org.openhab.ui.basic/web-src/settings.js
  bundles/org.openhab.ui.basic/web-src/smarthome.js
  bundles/org.openhab.ui.basic/web-src/static.js
  features/openhab-ui-external/src/main/resources/conf/basicui.cfg
Labels: enhancement, basic ui

#2445 Fix custom page icon size for openHAB icons
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: main ui, regression

#2446 Widget expressions: Improve `@` shorthand code
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: main ui

#2449 Settings menu: Fix back-link
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: main ui, regression

#2451 Improve Item name validation
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
Labels: enhancement, main ui

#2448 Items List: Remove Add item from textual
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: main ui

#2453 Item list & details: Hide group type if not set
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
Labels: bug, main ui

#2455 Channel edit: Fix regression causing editable channels to be locked
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-edit.vue
Labels: main ui, regression

#2454 Item edit: Align group's aggregation function
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
Labels: main ui

#2452 Item details: Fix editing groups with uneditable members & Sort members
  bundles/org.openhab.ui/web/src/components/item/group-members.vue
Labels: bug, main ui

#2470 Fix dirty warning shown on delete
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
Labels: bug, main ui

#2471 Rule edit: Code clean-ups
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-configure-module.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: main ui

#2473 Item edit: Check for type change & Fix dimension/unit change checks
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: bug, main ui

#2474 Item edit: Fix state description not saved for existing Item
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
Labels: bug, main ui

#2475 Thing edit: Fix changing ID shows wrong value & Always show UID
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
Labels: bug, main ui

#2450 Upgrade echarts and vue-echarts & Add fallback for visualMap when using heatmap
  bundles/org.openhab.ui/doc/components/oh-aggregate-series.md
  bundles/org.openhab.ui/doc/components/oh-calendar-series.md
  bundles/org.openhab.ui/doc/components/oh-data-series.md
  bundles/org.openhab.ui/doc/components/oh-time-series.md
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/index.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/chart/chart-designer.vue
  bundles/org.openhab.ui/web/src/components/thing/zwave/zwave-network.vue
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart-component.vue
Labels: enhancement, main ui

#2344 [BasicUI] Create header row only when needed
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ButtongridRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/MapviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/VideoRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/WebviewRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttongrid.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/header_row.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/mapview.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/video.html
  bundles/org.openhab.ui.basic/src/main/resources/snippets/webview.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2400 [mainui] Only load ignored inbox items in inbox view
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/add/choose-binding.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/add/choose-thing-type.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/inbox/inbox-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#2489 Upgrade Vue from 2.6.12 to 2.7.16
  bundles/org.openhab.ui/web/.eslintrc.js
  bundles/org.openhab.ui/web/jest.config.js
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/components/pagedesigner/widget-slot-config-popup.vue
Labels: enhancement, main ui

#2484 Fix webpack asset filename
  bundles/org.openhab.ui/web/build/webpack.config.js
Labels: main ui

#2487 Link channel to Item: Include error message on name validation failure
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: enhancement, main ui

#2476 [blockly] Fix missing event property causes JS error
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js
Labels: bug, main ui

#2495 Item edit: Validate name on load
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
Labels: enhancement, main ui

#2498 Fix deprecation warning in unit test
  bundles/org.openhab.ui/web/test/jest/__tests__/config-parameter.test.js
Labels: main ui

#2497 Rule edit: Always create script field for script action/condition
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: bug, main ui

#2499 Things list: Only show "no location" optionally for sort-by location
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#2500 Sitemap edit: Fix attribute-details styling applies globally
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/attribute-details.vue
Labels: bug, main ui

#2501 Things list: Fix location tab
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: main ui, regression

#2503 Upgrade dev dependencies
  bundles/org.openhab.ui/web/babel.config.js
  bundles/org.openhab.ui/web/build/build.js
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-dayofweek.vue
  bundles/org.openhab.ui/web/src/components/developer/help/context.vue
  bundles/org.openhab.ui/web/src/pages/addons/addon-details.vue
Labels: main ui

#2504 Make marked and diacritic dependencies and not dev dependencies
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: main ui

#2505 Rule edit: Fix rule module title and description regression
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: main ui, regression

#2506 Upgrade Framework7 to latest v5 version
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: main ui

#2508 Script edit: Fix dirty handling
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: bug, main ui

#2511 Analyzer: Fix analyzer not initially visible on iOS 17.4
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
  bundles/org.openhab.ui/web/src/pages/analyzer/analyzer.vue
Labels: bug, main ui

#2512 Things (inbox) list: Improve condition for reversed checkbox style
  bundles/org.openhab.ui/web/src/pages/settings/things/inbox/inbox-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#2513 Chart calendar axis: Don't override user-defined dayLabel and monthName settings
  bundles/org.openhab.ui/web/src/components/pagedesigner/chart/chart-designer.vue
  bundles/org.openhab.ui/web/src/components/widgets/chart/axis/oh-calendar-axis.js
Labels: bug, main ui

#2514 Downgrade vue-fragment as the upgrade broke oh-repeater in some circumstances
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: bug, main ui, regression

#2515 Things list: Fix broken list index after Thing removal
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: bug, main ui
