Repository openhab/openhab-webui, pull requests merged in 2024-02, with the labels that each got.

#2301 Widget expressions: (Partly) Fix handling of Item name being `undefined`
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: bug, main ui

#2303 Hide runtime errors and warnings from webpack dev server client overlay
  bundles/org.openhab.ui/web/build/webpack.config.js
Labels: main ui

#2305 `oh-block`: Allow setting style properties
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-block.vue
Labels: enhancement, main ui

#2314 Addon config page: Use dirty mixin & Add Ctrl-S shortcut
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/addons/addon-config.vue
Labels: bug, main ui

#2321 Fix code editor's Ruby detection
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
Labels: bug, main ui

#2316 [blockly] Fix warning when show code button is clicked twice
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: bug, main ui

#2308 [blockly] Fix typos in transformation block tooltip
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js
Labels: main ui

#2317 [blockly] Add tooltips to the show block/code buttons
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#2319 Disable Item editor fields for unmanaged items
  bundles/org.openhab.ui/web/src/components/config/controls/item-picker.vue
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: bug, main ui

#2311 [blockly] Set output type of oh_check_undefined_value to boolean
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-valuestorage.js
Labels: bug, main ui

#2313 Config sheet: Show advanced params if not default or not empty
  bundles/org.openhab.ui/web/src/components/config/config-sheet.vue
Labels: enhancement, main ui

#2328 Item details: Fix group member selection allows to select unmanaged Items
  bundles/org.openhab.ui/web/src/components/config/controls/item-picker.vue
  bundles/org.openhab.ui/web/src/components/item/group-members.vue
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
Labels: bug, main ui

#2329 Thing page: Fix dirty checks & Fix not-editable handling
  bundles/org.openhab.ui/web/src/components/thing/channel-link.vue
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: bug, main ui

#2320 Model picker popup: Add "Show name" and "Show tags" options
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/components/model/model-treeview.vue
Labels: enhancement, main ui

#2325 Item edit: Fix semantic class cleared when property set to None
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
Labels: bug, main ui

#2332 Settings page: Improve loading behaviour
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: bug, main ui

#2339 Fixes & Improvements to persistence edit, channel details & doc links logic
  bundles/org.openhab.ui/web/src/components/addons/addon-info-table.vue
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/help/context.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-alexa.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-ga.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-homekit.vue
  bundles/org.openhab.ui/web/src/js/store/index.js
  bundles/org.openhab.ui/web/src/pages/addons/addon-details.vue
  bundles/org.openhab.ui/web/src/pages/home/overview-tab.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/strategy-picker.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: main ui

#2338 Fix sidebar search scene and script integration
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/search-results.vue
Labels: bug, main ui

#2340 Allow custom page icons
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
Labels: enhancement, main ui

#2341 [BasicUI] Show buttons on several lines when not enough place
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttons.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: bug, basic ui

#2306 [blockly] Fix persistence block ZDT disconnection
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
Labels: bug, main ui

#2307 [blockly] Fix incorrect field names
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: bug, main ui

#2309 [blockly] Fix console warnings when switching to Math
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-math.js
Labels: bug, main ui

#2352 Rule edit: Remove redundant module title prefix
  bundles/org.openhab.ui/web/src/pages/settings/rules/module-description-suggestions.js
Labels: enhancement, main ui

#2350 Rule edit: Fix undefined currentSection error in trigger-module-wizard
  bundles/org.openhab.ui/web/src/components/rule/trigger-module-wizard.vue
Labels: bug, main ui

#2349 Remember checkbox settings in model picker popup
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
Labels: enhancement, main ui

#2348 Accept double click to pick a model in model picker popup
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
Labels: enhancement, main ui

#2304 Home edit: Fix model card settings drop-down not accessible
  bundles/org.openhab.ui/web/src/pages/settings/pages/home/home-edit.vue
Labels: bug, main ui

#2326 Improve item form layout
  bundles/org.openhab.ui/web/src/components/config/controls/item-picker.vue
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/model/item-details.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/components/rule/rule-general-settings.vue
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
  bundles/org.openhab.ui/web/src/components/tags/tag-input.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/chart/chart-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/map/map-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/plan/plan-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/tabs/tabs-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: enhancement, main ui

#2354 Thing create: Fix bridge can't be selected
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
Labels: main ui, regression

#2355 Model page: Remember checkbox settings
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: enhancement, main ui

#2358 Model page & Model Item picker: Don't remember "Show non-semantic" checkbox
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: main ui

#2360 Add back the 'When' prefix for file-based script trigger titles
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: main ui, regression

#2368 Help sidebar docs: Fix external anchors & Script editor RegEx
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/help/context.vue
Labels: bug, main ui

#2370 Add-on config page: Fix dirty handling
  bundles/org.openhab.ui/web/src/pages/addons/addon-config.vue
Labels: main ui

#2371 Persistence edit: Make page title dynamic & Fix delete back navigation
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: enhancement, main ui

#2367 Fix rule module editor popup for blockly
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: bug, main ui

#2372 Developer sidebar: Add clipboard icons
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/search-results.vue
Labels: enhancement, main ui

#2369 Add a global component developer-dock-icon
  bundles/org.openhab.ui/web/src/components/developer/developer-dock-icon.vue
  bundles/org.openhab.ui/web/src/js/app.js
  bundles/org.openhab.ui/web/src/pages/about.vue
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/schedule/schedule.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: main ui

#2362 Rule & Script editor: Various improvements
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/css/app.styl
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-general-settings.vue
Labels: enhancement, main ui

#2336 Label and style all UID elements consistently
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
  bundles/org.openhab.ui/web/src/components/rule/rule-general-settings.vue
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/add/thing-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-copy.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: enhancement, main ui

#2375 Item edit: Fix code tab not working properly
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: bug, main ui

#2377 Rule edit: Generate suggested trigger title only when none is available
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#2378 Developer sidebar icon: Check for admin role
  bundles/org.openhab.ui/web/src/components/developer/developer-dock-icon.vue
  bundles/org.openhab.ui/web/src/pages/home.vue
Labels: main ui, regression

#2380 Update links to the add-ons store
  bundles/org.openhab.ui/web/src/assets/definitions/help/help-qstart-defs.json
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/add/choose-binding.vue
Labels: bug, main ui

#2391 Persistence edit: Change empty-state-placeholder icon
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-settings.vue
Labels: enhancement, main ui

#2389 Fix semantics picker alignment class
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
Labels: main ui, regression

#2390 Sitemap editor: Add slider releaseOnly parameter support
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
Labels: enhancement, main ui

#2398 Fix link to persistence doc
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: main ui, regression

#2399 Persistence edit: Fix dirty for new persistence & Improve const handling
  bundles/org.openhab.ui/web/src/assets/definitions/persistence.js
  bundles/org.openhab.ui/web/src/assets/definitions/transformations.js
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
Labels: bug, main ui

#2288 Change the default navbar style from orange to light for light theme
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/theme-switcher.vue
Labels: main ui

#2405 Only align smart-select on wider screens
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: enhancement, main ui

#2402 Add support for SVG add-on logos
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-list-item.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-logo.vue
  bundles/org.openhab.ui/web/src/pages/addons/addon-details.vue
Labels: enhancement, main ui

#2407 Add-on store: Fix toolbar style & material design logo
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: main ui

#2408 Item edit: Fix dirty warning for not-editable Items
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/model/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: main ui

#2414 Overview tab: Fix javascript error
  bundles/org.openhab.ui/web/src/pages/home/overview-tab.vue
Labels: bug, main ui

#2421 Update alexa networking integration
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/deviceattributes.js
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/devicetypes.js
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/parameters.js
Labels: enhancement, main ui

#2422 Fix UID copy for not editable channels and transformations
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-general-settings.vue
Labels: bug, main ui

#2423 Help sidebar: Reduce list indentation
  bundles/org.openhab.ui/web/src/components/developer/help/context.vue
Labels: bug, main ui

#2403 Material theme: Fix lock icon is visible on editable items
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: main ui, regression

#2406 Add-on store: Title and searchbar focus tweaks
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: enhancement, main ui

#2412 Rule module popup: add dirty checking
  bundles/org.openhab.ui/web/src/pages/settings/dirty-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: enhancement, main ui

#2424 Help sidebar: Add blockly help page
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#2425 Location card: Swap status & measurement badges to avoid layout shift
  bundles/org.openhab.ui/web/src/components/cards/location-card.vue
Labels: enhancement, main ui

#2428 Item picker: Disable picker & hide chevron if not yet ready
  bundles/org.openhab.ui/web/src/components/config/controls/item-picker.vue
Labels: enhancement, main ui

#2411 [blockly] Provide HTTP request block
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/_tmp/blocks-http.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-dateoffsets.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-http.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/index.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#2430 Sidebar help: Use custom renderer instead of CSS for reduced list indentation
  bundles/org.openhab.ui/web/src/components/developer/help/context.vue
Labels: main ui

#2435 Add-on store: Minor logo styling tweaks
  bundles/org.openhab.ui/web/src/components/addons/addon-list-item.vue
  bundles/org.openhab.ui/web/src/pages/addons/addon-details.vue
Labels: main ui
