Repository openhab/openhab-webui, pull requests merged in 2024-12, with the labels that each got.

#2891 Channel copy: Fix changed config discarded
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-copy.vue
Labels: bug, main ui

#2892 Thing: Fix dirty warning shown on deletion if unsaved changes
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: bug, main ui

#2888 Config sheet: Always show advanced params only if changed from default
  bundles/org.openhab.ui/web/src/components/config/config-sheet.vue
Labels: enhancement, main ui

#2894 [BasicUI] Fix unit determination for min/max from item state description
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ColortemppickerRenderer.java
Labels: bug, basic ui

#2895 [BasicUI] Replace OK by CLOSE in the 2 color pop-ups
  bundles/org.openhab.ui.basic/snippets-src/main.html
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
Labels: enhancement, basic ui

#2896 Persistence edit: Support excluding items or groups
  bundles/org.openhab.ui/web/src/pages/settings/persistence/configuration-popup.vue
Labels: enhancement, main ui

#2908 Log viewer: Fix styling issues on mobile devices
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: bug, main ui

#2910 Fix safe-area issues
  bundles/org.openhab.ui/web/src/components/addons/addons-section.vue
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/css/app.styl
  bundles/org.openhab.ui/web/src/css/nomini.css
  bundles/org.openhab.ui/web/src/js/app.js
  bundles/org.openhab.ui/web/src/pages/home/model-tab.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: bug, main ui

#2911 Update openhab-js tern defs
  bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
Labels: enhancement, main ui

#2912 Update unit definitions
  bundles/org.openhab.ui/web/src/assets/units.js
Labels: enhancement, main ui

#2913 Unit metadata edit: Add missing padding
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-unit.vue
Labels: bug, main ui

#2905 Log viewer: only render lines around visible area
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: bug, main ui

#2928 Fix scripting add-on availability check for old JS Scripting MIME type
  bundles/org.openhab.ui/web/src/components/rule/module-wizard-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: bug, main ui, patch

#2931 `oh-card`: Fix action & tap-hold action not working
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-card.vue
Labels: bug, main ui

#2932 `oh-clock-card`: Remove (broken) background property in favour of style config
  bundles/org.openhab.ui/doc/components/oh-clock-card.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/standard/cards.js
Labels: bug, main ui

#2933 Widget expressions: Fix screen object not properly initialized & updated
  bundles/org.openhab.ui/web/src/components/widgets/widget-expression-mixin.js
Labels: bug, main ui

#2938 Fix enabled profiles in link editor appear disabled
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
Labels: bug, main ui

#2915 Import treeview items locally & Clean-up sitemap page components
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/model/model-treeview.vue
  bundles/org.openhab.ui/web/src/components/model/treeview-item.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
  bundles/org.openhab.ui/web/src/components/sitemap/widget-generic.vue
  bundles/org.openhab.ui/web/src/js/app.js
  bundles/org.openhab.ui/web/src/pages/page/sitemap-view.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2941 Link add/edit: Fix profile selection
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-mixin.js
Labels: bug, main ui

#2948 Interactive SVG add String Type support
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
Labels: enhancement, main ui

#2904 Sitemap editor: Add drag & drop
  bundles/org.openhab.ui/web/.vscode/settings.json
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/sitemap-code.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/sitemap-mixin.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2949 Don't subscribe to Item events to reload model
  bundles/org.openhab.ui/web/src/components/sse-events-mixin.js
Labels: bug, main ui

#2950 Thing details: Fix Z-Wave network map shown if not Z-Wave binding
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: bug, main ui

#2953 Page: Add ability to edit current tab of tabbed page
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
Labels: enhancement, main ui

#2958 Allow item names to start with an underscore
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
Labels: bug, main ui

#2946 Enable additional chart types for `oh-data-series`
  bundles/org.openhab.ui/doc/components/oh-data-series.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/index.js
Labels: enhancement, main ui

#2959 Layout pages: Safe area fixes & related code improvements
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-card.vue
  bundles/org.openhab.ui/web/src/css/app.styl
  bundles/org.openhab.ui/web/src/css/nomini.css
Labels: bug, main ui

#2907 Refactor websocket code to `$oh` namespace & Pass access token through header
  bundles/org.openhab.ui/web/src/js/openhab/index.js
  bundles/org.openhab.ui/web/src/js/openhab/ws.js
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui
