Repository openhab/openhab-webui, pull requests merged in 2024-01, with the labels that each got.

#2238 [BasicUI] Fix image element being link to a sub page
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2247 [BasicUI] Enhance the description of the "Inline SVG" setting
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
Labels: enhancement, basic ui

#2246 Improve network-interface context support
  bundles/org.openhab.ui/web/src/components/config/config-parameter.vue
Labels: main ui

#2257 [BaiscUI] Adjust the SVG icon in buttons to the current theme
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2260 [BasicUI] Fix Buttongrid alignment on desktop
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttongrid.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/_theming.scss
Labels: bug, basic ui

#2269 [BasicUI] Update the content of the default cfg file
  features/openhab-ui-external/src/main/resources/conf/basicui.cfg
Labels: bug, basic ui

#2270 oh-colorpicker: Replace defaultColor option with an actual default color
  bundles/org.openhab.ui/doc/components/oh-colorpicker-card.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-cell.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-item.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/colorpicker.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-colorpicker.vue
Labels: enhancement, main ui

#2277 Thing edit: Hide clear button for location if not editable or not ready
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
Labels: bug, main ui

#2273 Update descriptions in the settings menu
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: enhancement, main ui

#2280 [BasicUI] Fix SSE reconnection to the current page
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2282 [BasicUI] Close EventSource when leaving
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: basic ui

#2289 Settings page: Fix add-on settings header displayed when no add-ons installed
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: bug, main ui

#2290 Help Feature FAQ: Remove persistence FAQs
  bundles/org.openhab.ui/web/src/assets/definitions/help/help-faq-defs.json
Labels: main ui

#2253 Help sidebar: Move docs to docs repo & Integrate them into the UI
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/help/addon-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/default-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/item-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/model-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/page-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/rule-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/thing-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/transform-context.vue
  bundles/org.openhab.ui/web/src/components/developer/help/widget-context.vue
  bundles/org.openhab.ui/web/src/pages/about.vue
  bundles/org.openhab.ui/web/src/pages/addons/addon-details.vue
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-settings.vue
Labels: enhancement, main ui

#2291 Home page: Hide tab bar if all model tabs are hidden
  bundles/org.openhab.ui/web/src/pages/home.vue
Labels: bug, main ui

#2284 [BasicUI] Replace non printable characters
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2276 Rule/Script edit: Fix not editable not properly handled & Always show tags
  bundles/org.openhab.ui/web/src/components/rule/rule-general-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-general-settings.vue
Labels: bug, main ui

#2295 Transformation edit: Fix copy UID doesn't work
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformation-edit.vue
Labels: bug, main ui

#2096 Fix `oh-stepper` sends command on Item state update due to rounding
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-stepper.vue
Labels: bug, main ui

#2296 Update alexa range value attribute parameters
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/deviceattributes.js
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/devicetypes.js
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/helpers.js
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/alexa/parameters.js
Labels: enhancement, main ui

#2267 Upgrade from webpack v4 to v5
  .github/workflows/mainui.yml
  README.md
  bundles/org.openhab.ui.basic/CONTRIBUTING.md
  bundles/org.openhab.ui.habot/CONTRIBUTING.md
  bundles/org.openhab.ui.habpanel/CONTRIBUTING.md
  bundles/org.openhab.ui/CONTRIBUTING.md
  bundles/org.openhab.ui/pom.xml
  bundles/org.openhab.ui/web/babel.config.js
  bundles/org.openhab.ui/web/build/webpack.config.js
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/_tmp/blocks-exec.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/_tmp/blocks-http.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-audio.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-color.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-dateoffsets.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-dicts.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-ephemeris.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-eventbus.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-items.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-list.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-logging.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-math.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-metadata.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-notifications.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-scripts.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-text.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-things.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-timers.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-uom.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-valuestorage.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/libraries.js
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/utils.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
  bundles/org.openhab.ui/web/src/pages/developer/blocks/blocks-edit.vue
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue
  bundles/org.openhab.ui/web/src/service-worker.js
Labels: main ui
