Repository openhab/openhab-webui, pull requests merged in 2024-06, with the labels that each got.

#2533 Add oh-context component
  bundles/org.openhab.ui/doc/components/index.md
  bundles/org.openhab.ui/doc/components/oh-context.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/context.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/index.js
  bundles/org.openhab.ui/web/src/components/config/editor/hint-components.js
  bundles/org.openhab.ui/web/src/components/widgets/modals/modal-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/system/index.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-button.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-context.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-gauge.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-link.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-stepper.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-toggle.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/slide-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/variable-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-expression-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
  bundles/org.openhab.ui/web/src/pages/developer/widgets/widget-edit.vue
Labels: enhancement, main ui

#2599 Widget expressions: Ensure correct context & props are passed on recursion
  bundles/org.openhab.ui/web/src/components/widgets/widget-expression-mixin.js
Labels: bug, main ui

#2600 Add-on store: Fix region is null error
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: bug, main ui

#2610 Fix Main UI dark mode scrollbars in Chrome
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: bug, main ui

#2611 Sitemap edit: Fix column width wrongly applied
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: bug, main ui

#2614 Thing view: Add support for HTML-formatting of channel descriptions
  bundles/org.openhab.ui/web/src/components/thing/channel-group.vue
Labels: enhancement, main ui

#2618 Rule module popup: Fix margin issue with Configuration block title
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: bug, main ui

#2620 Rule module popup: Fix margin issues and improve styling
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: bug, main ui

#2624 Things list: Reload on ThingUpdatedEvent
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#2622 [MainUI] exposes navigation commands to native wrappers
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/sse-events-mixin.js
Labels: enhancement, main ui

#2627 Update openhab-js tern defs
  bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
Labels: enhancement, main ui

#2628 Rename rule/scene/script name to label for consistency
  bundles/org.openhab.ui/web/src/components/rule/rule-general-settings.vue
Labels: enhancement, main ui

#2629 Setup wizard: Add InMemory persistence to recommended add-ons
  bundles/org.openhab.ui/web/src/assets/i18n/setup-wizard/en.json
  bundles/org.openhab.ui/web/src/pages/wizards/setup-wizard.vue
Labels: enhancement, main ui

#2630 Cron expression builder: Set day 1 as Sunday
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/components/config/controls/cronexpression-editor.vue
Labels: bug, main ui

#2631 Analyzer: Fix silent failure if no items are set
  bundles/org.openhab.ui/doc/components/oh-aggregate-series.md
  bundles/org.openhab.ui/doc/components/oh-button.md
  bundles/org.openhab.ui/doc/components/oh-calendar-axis.md
  bundles/org.openhab.ui/doc/components/oh-calendar-series.md
  bundles/org.openhab.ui/doc/components/oh-cell.md
  bundles/org.openhab.ui/doc/components/oh-clock-card.md
  bundles/org.openhab.ui/doc/components/oh-colorpicker-cell.md
  bundles/org.openhab.ui/doc/components/oh-data-series.md
  bundles/org.openhab.ui/doc/components/oh-gauge-card.md
  bundles/org.openhab.ui/doc/components/oh-icon.md
  bundles/org.openhab.ui/doc/components/oh-image-card.md
  bundles/org.openhab.ui/doc/components/oh-image.md
  bundles/org.openhab.ui/doc/components/oh-knob-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-card.md
  bundles/org.openhab.ui/doc/components/oh-label-cell.md
  bundles/org.openhab.ui/doc/components/oh-label-item.md
  bundles/org.openhab.ui/doc/components/oh-link.md
  bundles/org.openhab.ui/doc/components/oh-list-item.md
  bundles/org.openhab.ui/doc/components/oh-map-circle-marker.md
  bundles/org.openhab.ui/doc/components/oh-map-marker.md
  bundles/org.openhab.ui/doc/components/oh-plan-marker.md
  bundles/org.openhab.ui/doc/components/oh-rollershutter-cell.md
  bundles/org.openhab.ui/doc/components/oh-slider-cell.md
  bundles/org.openhab.ui/doc/components/oh-time-series.md
  bundles/org.openhab.ui/doc/components/oh-video.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/actions.js
  bundles/org.openhab.ui/web/src/assets/i18n/analyzer/en.json
  bundles/org.openhab.ui/web/src/pages/analyzer/analyzer.vue
Labels: bug, main ui

#2632 Group item form: Add missing COUNT aggregation function
  bundles/org.openhab.ui/web/src/assets/item-types.js
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
Labels: bug, enhancement

#2633 oh-input: Fix select with options & setting style not working
  bundles/org.openhab.ui/doc/components/images/oh-input/select-options.png
  bundles/org.openhab.ui/doc/components/oh-input.md
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
Labels: bug, main ui

#2623 Rules list: Improve performance of rule status tracking
  bundles/org.openhab.ui/web/src/components/rule/rule-status-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
Labels: bug, main ui

#2634 oh-input: Allow overwriting calendarParams defaults for datepicker
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
Labels: bug, main ui

#2635 oh-sipclient: Add auto answer & auto dial features
  bundles/org.openhab.ui/doc/components/oh-sipclient-card.md
  bundles/org.openhab.ui/doc/components/oh-sipclient.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/sipclient.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue
Labels: enhancement, main ui

#2420 Add UI for health checks (broken links)
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/health/health-orphanlinks.vue
  bundles/org.openhab.ui/web/src/pages/settings/health/health-overview.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: enhancement, main ui

#2596 [blockly] Persistence: Enhance existing blocks & add blocks to cover all available actions
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui
