Repository openhab/openhab-webui, pull requests merged in 2024-04, with the labels that each got.

#2492 [BasicUI] All buttons forced on one line for a Player item
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/buttons.html
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: enhancement, basic ui

#2524 [BasicUI] Add predefined periods in future for chart
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2526 Thing details: Fix code tab not editable
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: bug, main ui, regression

#2539 Things list: Always show the inbox
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#2540 SSE Item State Tracking: Avoid requesting __ob__ and __v_isRef
  bundles/org.openhab.ui/web/src/components/cards/glance/glance-helpers.js
  bundles/org.openhab.ui/web/src/js/store/modules/states.js
Labels: bug, main ui, regression

#2541 Persistence edit: Add support for selecting all Items
  bundles/org.openhab.ui/web/src/pages/settings/persistence/configuration-popup.vue
Labels: enhancement, main ui

#2542 Script edit: Fix script creation fails due to exception
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: bug, main ui, regression

#2538 [BasicUI] Fix update of buttons (switch element)
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2543 Metadata: Add `link_to_more` as well-known namespace
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/namespaces.js
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-linktomore.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
Labels: enhancement, main ui

#2485 Save stateDescriptionPattern from channel type for UoM Items & Save UoM metadata when adding from model
  bundles/org.openhab.ui/web/src/components/item/group-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/item/item-mixin.js
  bundles/org.openhab.ui/web/src/components/thing/channel-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-thing.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: enhancement, main ui

#2535 [BasicUI] Fix slider behaviour and implement two different modes
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SliderRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/slider.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, enhancement, basic ui

#2548 Charts: Fix initial period wrongly calculated for future charts
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
Labels: bug, main ui

#2534 [BasicUI] Add special handling for "none" icon
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/AbstractWidgetRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/snippets/icon_none.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2554 Sitemap editor: Fix buttongrid editor
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/attribute-details.vue
Labels: bug, main ui

#2555 Add-on logo component: Make lazy loading optional
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-list-item.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-logo.vue
Labels: enhancement, main ui

#2434 Use Node v20 for Main UI build
  .github/workflows/ci-build.yml
  .github/workflows/mainui.yml
  bundles/org.openhab.ui/CONTRIBUTING.md
  bundles/org.openhab.ui/pom.xml
  bundles/org.openhab.ui/web/.nvmrc
Labels: main ui
