Repository openhab/openhab-webui, pull requests merged in 2024-11, with the labels that each got.

#2850 Thing action popup: Improve rendering of output value
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-action-popup.vue
Labels: main ui

#2853 oh-cell: Fix safe-area issues
  bundles/org.openhab.ui/web/src/css/app.styl
Labels: bug, main ui

#2854 Rule/Scene/Script edit: Block addition of reserved tags
  bundles/org.openhab.ui/web/src/components/tags/tag-input.vue
Labels: enhancement, main ui

#2855 Implement copy functionality for Things, Items, scenes & scripts
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/add/thing-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: enhancement, main ui

#2856 Pages list: Don't allow selecting overview page for removal
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
Labels: bug, main ui

#2858 Thing copy: Keep label
  bundles/org.openhab.ui/web/src/pages/settings/things/add/thing-add.vue
Labels: main ui

#2859 Add-ons store: Improve card sizing on desktop
  bundles/org.openhab.ui/web/src/components/addons/addons-section.vue
  bundles/org.openhab.ui/web/src/components/addons/addons-swiper.vue
Labels: enhancement, main ui

#2861 Model (picker): Fix toolbar checkbox issues with safe areas
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: bug, main ui

#2860 oh-colorpicker: Fix color picker sends commands on external state change
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-colorpicker.vue
Labels: bug, main ui

#2851 [BasicUI] Implement new sitemap element Colortemperaturepicker
  bundles/org.openhab.ui.basic/snippets-src/colortemppicker.html
  bundles/org.openhab.ui.basic/snippets-src/main.html
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ColortemppickerRenderer.java
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/servlet/WebAppServlet.java
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2863 Config param time & datetime: Fix seconds support
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-datetime.vue
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-time.vue
Labels: main ui

#2787 Canvas layout: Add interactive SVG support
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/layout/index.js
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-layout.vue
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-layout-page.vue
  bundles/org.openhab.ui/web/src/js/openhab/utils.js
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
Labels: enhancement, main ui

#2864 oh-canvas: Fix exception on empty initial svg config
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
Labels: bug, main ui

#2865 Thing action popup: Fix invocation of action with signature hash
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-action-popup.vue
Labels: bug, main ui

#2866 Fix hsbToRgb util & Fix conversion in oh-canvas-embedded-svg-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
  bundles/org.openhab.ui/web/src/js/openhab/utils.js
Labels: bug, main ui

#2867 Thing actions: Respect action visibility
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: enhancement, main ui

#2869 oh-image-card: Fix too much padding when no action configured
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-image-card.vue
Labels: bug, main ui

#2874 oh-label-card: Hide label if no label or Item configured
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-label-card.vue
Labels: bug, main ui

#2872 Interactive SVG background: process whole SVG group for state
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
Labels: enhancement, main ui

#2871 [BasicUI] Fix selection of color temperature near min and max
  bundles/org.openhab.ui.basic/snippets-src/colortemppicker.html
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: bug, basic ui

#2873 [BasicUI] Add preview color to Colorpicker widget
  bundles/org.openhab.ui.basic/snippets-src/colorpicker.html
  bundles/org.openhab.ui.basic/snippets-src/colortemppicker.html
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ColorpickerRenderer.java
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2388 [BasicUI] Align and optimize available space for switch with mappings
  bundles/org.openhab.ui.basic/snippets-src/buttons.html
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/SwitchRenderer.java
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#2880 Sitemap editor: Add support for color temperature picker
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/sitemap-mixin.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/__tests__/sitemap-edit_jest.spec.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#2886 Widget action taphold: Hide context menu in desktop browser
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
Labels: bug, main ui
