Repository openhab/openhab-webui, pull requests merged in 2025-05, with the labels that each got.

#3143 [BasicUI] Shrink labels before values
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: bug, basic ui

#3182 [BasicUI] Enable dynamic icons for Chart element
  bundles/org.openhab.ui.basic/snippets-src/chart.html
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
Labels: bug, basic ui

#3169 Add mime type & code snippet for PY transformation
  bundles/org.openhab.ui/web/src/assets/transformations.js
Labels: enhancement, main ui

#3173 Thing Edit: Thing UID should not change when bridge is changed
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
Labels: bug, main ui, regression

#3175 Add Widget: Sort Personal Widgets
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
Labels: enhancement, main ui

#3170 Left Menu: Enable shortcut also when pinned but hidden
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: enhancement, main ui

#3174 Rule Module Popup: Hide Save link on inline script language selection
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
Labels: bug, main ui

#3172 Log Viewer: Add next/prev to log details popup and make it movable
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui

#3184 Sitemap editor: Small fixes & Add duplicate element functionality
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: enhancement, main ui

#3177 Log Viewer: Add text mode option
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui

#3193 Fix Python syntax highlighting
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
Labels: bug, main ui

#3194 Sitemap editor: Various fixes
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/sitemap-mixin.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: bug, main ui

#3179 Charts: Add oh-state-series to render state transitions over time
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/index.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/chart/chart-designer.vue
  bundles/org.openhab.ui/web/src/components/widgets/chart/axis/oh-category-axis.js
  bundles/org.openhab.ui/web/src/components/widgets/chart/chart-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/chart/series/oh-state-series.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart-component.vue
Labels: enhancement, main ui

#2970 Model editor: Add drag & drop
  bundles/org.openhab.ui/web/src/components/item/item.vue
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/components/model/model-treeview.vue
  bundles/org.openhab.ui/web/src/components/model/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-template.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model-dragdrop-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/model/model-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: enhancement, main ui

#3195 Widget actions: Add aggregation type parameter for analyzer action
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/actions.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/index.js
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/chart/options.js
  bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js
  bundles/org.openhab.ui/web/src/pages/analyzer/analyzer.vue
Labels: enhancement, main ui

#3196 Analyzer: Add comment to silent series option
  bundles/org.openhab.ui/web/src/pages/analyzer/analyzer.vue
Labels: main ui

#3199 Model editor: drag drop fixes
  bundles/org.openhab.ui/web/src/components/model/model-treeview.vue
  bundles/org.openhab.ui/web/src/components/model/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model-dragdrop-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/model/model-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/model/model.vue
Labels: bug, main ui

#3129 Add Matter metadata
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/matter.js
  bundles/org.openhab.ui/web/src/assets/definitions/metadata/namespaces.js
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-matter.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
Labels: enhancement, main ui
