Repository openhab/openhab-webui, pull requests merged in 2025-04, with the labels that each got.

#3112 Addon Card: Give title has more room to avoid overflow
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
  bundles/org.openhab.ui/web/src/components/addons/addon-stats-line.vue
Labels: enhancement, main ui

#3069 Sitemap editor: Add chart interpolation parameter
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/sitemap-mixin.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/widget-details.vue
Labels: enhancement, main ui

#3127 Don't use virtual lists where not necessary
  bundles/org.openhab.ui/web/src/pages/settings/persistence/filter-picker.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/strategy-picker.vue
Labels: enhancement, main ui

#3128 Help sidebar: Add log viewer docs
  bundles/org.openhab.ui/web/src/components/developer/help-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/help/context.vue
Labels: enhancement, main ui

#3050 oh-input: Fix editing a number item with unit & Several enhancements
  bundles/org.openhab.ui/doc/components/oh-input-card.md
  bundles/org.openhab.ui/doc/components/oh-input-item.md
  bundles/org.openhab.ui/doc/components/oh-input.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/input.js
  bundles/org.openhab.ui/web/src/components/widgets/standard/list/oh-input-item.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
Labels: enhancement, main ui

#3131 Widgets: Fix check for action not checking actionPropsParameterGroup
  bundles/org.openhab.ui/web/src/components/widgets/standard/cell/oh-cell.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/list/oh-list-item.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-gauge-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-image-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-label-card.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-button.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-image.vue
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-link.vue
  bundles/org.openhab.ui/web/src/components/widgets/widget-mixin.js
Labels: bug, main ui

#3132 oh-icon: Fix action not working for f7 & iconify icons
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-icon.vue
Labels: bug, main ui

#3133 Link add/edit: Fix link Dimmer/Switch Items to Color channel
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-mixin.js
Labels: bug, main ui

#3134 Link add/edit: Fix link String Items to any channel
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-mixin.js
Labels: bug, main ui

#3135 Log viewer: Fix copy to clipboard not working
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: bug, main ui

#3137 Upgrade (Vue) Echarts
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: enhancement, main ui

#3136 oh-chart-component: Register & Use configured locale for Echarts
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-chart-component.vue
Labels: enhancement, main ui

#2893 [blockly] Riemann sum persistence extension and js tern definitions
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
  bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
Labels: enhancement, main ui

#3092 Parameter-text redesign for multiple text values
  bundles/org.openhab.ui/web/src/components/config/controls/parameter-text.vue
Labels: enhancement, main ui

#3141 Link add/edit: Fix config-sheet not properly re-rendered on profile type change
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
Labels: bug, main ui

#3148 [BasicUI] Remove top/bottom margins in buttons-multiline
  bundles/org.openhab.ui.basic/web-src/_layout.scss
Labels: bug, basic ui

#3147 [BasicUI] Add a setting to render buttons with rounded corners
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/PageRenderer.java
  bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.ui.basic/web-src/_layout.scss
  bundles/org.openhab.ui.basic/web-src/settings.js
  bundles/org.openhab.ui.basic/web-src/smarthome.js
Labels: enhancement, basic ui

#3145 Inbox List: Add select all / deselect all
  bundles/org.openhab.ui/web/src/pages/settings/things/inbox/inbox-list.vue
Labels: enhancement, main ui

#3124 Create equipment from model: Use semanticEquipmentTag of Thing
  bundles/org.openhab.ui/web/src/pages/settings/model/add-from-thing.vue
Labels: enhancement, main ui

#3144 Items List: Add select all / deselect all
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: enhancement, main ui

#3152 Align search behaviour in case of nothing found
  bundles/org.openhab.ui/web/src/pages/settings/pages/pages-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: enhancement, main ui

#3070 Persistence edit: Support configuring aliases
  bundles/org.openhab.ui/web/src/components/config/controls/item-picker.vue
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: enhancement, main ui

#3149 Item edit: Relabel category to icon
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: enhancement, main ui

#3142 Remove ESLintPlugin from webpack build
  bundles/org.openhab.ui/web/build/webpack.config.js
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
Labels: main ui

#3159 Sidebar Search: Fix rules/scenes/scripts search result count
  bundles/org.openhab.ui/web/src/components/developer/search-results.vue
Labels: bug, main ui

#3158 Show thing firmware status
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: enhancement, main ui

#3130 File Definition: Add Copy Thing YAML file definition
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
  bundles/org.openhab.ui/web/src/pages/settings/file-definition-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/inbox/inbox-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-inbox-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#3163 Copy File Definition: Process multiple objects with single api request
  bundles/org.openhab.ui/web/src/js/openhab/api.js
  bundles/org.openhab.ui/web/src/pages/settings/file-definition-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/items/items-list-vlist.vue
Labels: enhancement, main ui

#3164 Developer Sidebar: make pinned objects persistent
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: enhancement, main ui

#3160 Add log details popup
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui
