Repository openhab/openhab-webui, pull requests merged in 2025-08, with the labels that each got.

#3306 Sitemap parser: Further fixes for icon rules
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
Labels: bug, main ui, backported

#3313 Developer Sidebar: Add rule.trigger.configuration.groupName to the search
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: bug, main ui, backported, backported4

#3289 Developer Sidebar: Support advanced search syntax
  bundles/org.openhab.ui/web/package-lock.json
  bundles/org.openhab.ui/web/package.json
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
Labels: enhancement, main ui

#3307 Semantic tags page: Fix page refresh & delete synonym bugs
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/js/store/modules/semantics.js
  bundles/org.openhab.ui/web/src/pages/developer/semantics/semantic-tags-edit.vue
Labels: bug, main ui, backported

#3322 oh-sipclient: Add config for authorization user
  bundles/org.openhab.ui/doc/components/oh-sipclient-card.md
  bundles/org.openhab.ui/doc/components/oh-sipclient.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/sipclient.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue
Labels: enhancement, main ui

#3316 [HABot] Add support for configurable HumanLanguageInterpreter (HLI) in HABot
  bundles/org.openhab.ui.habot/src/main/java/org/openhab/ui/habot/rest/internal/HABotResource.java
Labels: enhancement, habot ui

#3339 Sitemap editor: Fix sitemap save
  bundles/org.openhab.ui/web/src/pages/settings/pages/sitemap/sitemap-edit.vue
Labels: bug, main ui
