Repository openhab/openhab-webui, pull requests merged in 2025-03, with the labels that each got.

#3078 blockly: set value to key of dictionary
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-dicts.js
  bundles/org.openhab.ui/web/src/components/config/controls/blockly-editor.vue
Labels: enhancement, main ui

#3087 Script Editor: Fix editing RulesDSL scripts
  bundles/org.openhab.ui/web/src/assets/automation-languages.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: bug, main ui, regression

#3082 [blockly ]oh_taggeditems block: Fix multiple tags in vars & Add array support
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-items.js
Labels: enhancement, main ui

#3081 Add Alt-Shift-M shortcut key to toggle menu when unpinned
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: enhancement, main ui

#3095 Minor enhancements to Main UI CI job
  .github/workflows/mainui.yml
Labels: main ui

#3098 Script edit: Automatically update GraalJS mime type when opening script
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#3047 Location Picker: Set default to system location, otherwise set to worldwide zoom level
  bundles/org.openhab.ui/web/src/components/config/controls/location-picker.vue
Labels: enhancement, main ui

#3099 i18n: Add support for loading locales from multiple scopes
  bundles/org.openhab.ui/web/src/js/i18n.js
Labels: enhancement, main ui

#3058 Use a more specific browser title for each page
  bundles/org.openhab.ui/web/src/components/app.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
Labels: enhancement, main ui

#3089 Model Item Details: `View/Hide Details` instead of `Edit` for uneditable Items
  bundles/org.openhab.ui/web/src/components/model/item-details.vue
Labels: enhancement, main ui

#3020 Things List: Add multiple search, select all & Inbox: Go to newly approved Thing(s)
  bundles/org.openhab.ui/web/src/css/app.styl
  bundles/org.openhab.ui/web/src/pages/settings/things/add/choose-thing-type.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/inbox/inbox-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-inbox-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/things/things-list.vue
Labels: enhancement, main ui

#3056 Layout edit: Move page settings to bottom of screen in edit mode
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/layout/layout-edit.vue
Labels: enhancement, main ui

#3100 Script edit: Fix minor styling issue in script details
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: bug, main ui

#3101 Location card: Support Lightbulb & LightStripes equipment for lights status badge
  bundles/org.openhab.ui/web/src/components/cards/glance/location/status-badge.vue
Labels: enhancement, main ui

#2997 Event WS client: Filter by topic instead of type
  bundles/org.openhab.ui/web/src/js/openhab/ws.js
Labels: enhancement, main ui

#3039 Widget Config and Widget Code: Live update, dirty checking, movable popup
  bundles/org.openhab.ui/web/src/components/pagedesigner/widget-code-popup.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/widget-config-popup.vue
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue
  bundles/org.openhab.ui/web/src/pages/settings/movable-popup-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/pages/pagedesigner-mixin.js
Labels: enhancement, main ui

#3086 Thing Details: Add Copy DSL Definition button
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/components/thing/channel-link.vue
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/items/item-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/scene/scene-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-duplicate.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-textual-definition.js
Labels: enhancement, main ui

#3085 Developer Tools: Add Copy DSL Definition for Items and Things
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
Labels: enhancement, main ui

#3113 Add-on card: Add tooltip to label
  bundles/org.openhab.ui/web/src/components/addons/addon-card.vue
Labels: enhancement, main ui

#3114 Config sheet: Fix loading of multi-line default values
  bundles/org.openhab.ui/web/src/components/config/config-sheet.vue
Labels: bug, main ui

#3105 Persistence edit: Fix multiple selection
  bundles/org.openhab.ui/web/src/pages/settings/persistence/configuration-popup.vue
Labels: bug, main ui

#3110 Developer sidebar: Add ability to search and pin widgets
  bundles/org.openhab.ui/web/src/components/developer/developer-sidebar.vue
  bundles/org.openhab.ui/web/src/components/developer/search-results.vue
Labels: enhancement, main ui

#3118 Persistence edit: Add missing dirty checking on edit
  bundles/org.openhab.ui/web/src/pages/settings/persistence/persistence-edit.vue
Labels: bug, main ui

#3119 oh-card: Indicate that card is clickable if action is configured
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-card.vue
Labels: bug, main ui

#3116 Main UI mvn build: Various enhancements to improve DX in Eclipse IDE
  bundles/org.openhab.ui/CONTRIBUTING.md
  bundles/org.openhab.ui/pom.xml
  bundles/org.openhab.ui/web/build/build.js
  bundles/org.openhab.ui/web/build/webpack.config.js
  bundles/org.openhab.ui/web/package.json
Labels: main ui
