Repository openhab/openhab-webui, pull requests merged in 2025-06, with the labels that each got.

#3197 Regenerate rule templates
  bundles/org.openhab.ui/web/src/assets/i18n/common/en.json
  bundles/org.openhab.ui/web/src/assets/i18n/rule-status/en.json
  bundles/org.openhab.ui/web/src/components/config/controls/script-editor.vue
  bundles/org.openhab.ui/web/src/components/rule/action-module-wizard.vue
  bundles/org.openhab.ui/web/src/components/rule/condition-module-wizard.vue
  bundles/org.openhab.ui/web/src/components/rule/rule-general-settings.vue
  bundles/org.openhab.ui/web/src/components/rule/rule-status-mixin.js
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/dirty-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/module-description-suggestions.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-module-popup.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-general-settings.vue
Labels: enhancement, main ui

#3226 Make Main UI log levels configurable
  bundles/org.openhab.ui/web/src/js/app.js
  bundles/org.openhab.ui/web/src/js/logging.js
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
Labels: enhancement, main ui

#3234 [Blockly] Fix blockly persistence code generation
  bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
Labels: bug, main ui

#3213 oh-colorpicker: Fix sliders not initialized in widget
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-colorpicker.vue
Labels: bug, main ui

#3241 Fix Matter metadata configuration options for group members
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-matter.vue
Labels: bug, main ui

#3247 Allow float values for widget order
  bundles/org.openhab.ui/web/src/components/widgets/widget-order.js
Labels: bug, main ui, regression

#3249 Item metadata: Fix metadata from uneditable Items is editable
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-alexa.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-autoupdate.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-expire.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-ga.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-homekit.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-itemdescription.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-linktomore.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-matter.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-menu.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-synonyms.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-unit.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-voicesystem.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-widget.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-widgetorder.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
Labels: bug, main ui

#3250 Item metadata: Use editable field of REST response
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-alexa.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-autoupdate.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-expire.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-ga.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-homekit.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-itemdescription.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-linktomore.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-matter.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-menu.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-mixin.js
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-synonyms.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-unit.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-voicesystem.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-widget.vue
  bundles/org.openhab.ui/web/src/components/item/metadata/item-metadata-widgetorder.vue
  bundles/org.openhab.ui/web/src/pages/settings/items/metadata/item-metadata-edit.vue
Labels: enhancement, main ui

#3202 Add semantic model warnings to health UI
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/pages/settings/health/health-overview.vue
  bundles/org.openhab.ui/web/src/pages/settings/health/health-semantics.vue
  bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
Labels: enhancement, main ui

#3223 Model treeview: Fixes for drag and drop
  bundles/org.openhab.ui/web/src/components/model/model-picker-popup.vue
  bundles/org.openhab.ui/web/src/components/model/model-treeview.vue
  bundles/org.openhab.ui/web/src/components/model/treeview-item.vue
  bundles/org.openhab.ui/web/src/pages/settings/model/model-dragdrop-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/model/model-mixin.js
Labels: bug, main ui

#3245 Location card: Various improvements and fixes
  bundles/org.openhab.ui/web/src/components/cards/glance/glance-helpers.js
  bundles/org.openhab.ui/web/src/components/cards/glance/location/status-badge.vue
Labels: enhancement, main ui
