Repository openhab/openhab-webui, pull requests merged in 2025-01, with the labels that each got.

#2965 Widget expressions: Fix handling of Item name being `undefined` & Align behaviour for @ and @@ shorthands in that case
  bundles/org.openhab.ui/web/src/components/widgets/widget-expression-mixin.js
  bundles/org.openhab.ui/web/src/js/store/modules/states.js
Labels: bug, main ui

#2976 WS client: Remove trailing `=` from base64-encoded access token
  bundles/org.openhab.ui/web/src/js/openhab/ws.js
Labels: bug, main ui

#2969 Fix Schedule page shows UTC instead of local timezone
  bundles/org.openhab.ui/web/src/pages/settings/schedule/schedule.vue
Labels: bug, main ui, patch

#2981 Developer tools: Add WS connection test
  bundles/org.openhab.ui/web/build/webpack.config.js
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
Labels: enhancement, main ui

#2982 Tag Input: Fix automatic add on blur
  bundles/org.openhab.ui/web/src/components/tags/tag-input.vue
Labels: bug, main ui

#2991 Chart page: Fix wrong height inside popups, popovers & sheets on iOS
  bundles/org.openhab.ui/web/src/components/widgets/chart/oh-chart-page.vue
Labels: bug, main ui

#2992 Chart page: Fix wrong height and top position in sheets
  bundles/org.openhab.ui/web/src/components/widgets/chart/oh-chart-page.vue
Labels: bug, main ui

#2993 WS client: Add convenience method to connect to the event WebSocket
  bundles/org.openhab.ui/web/src/js/openhab/ws.js
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui

#2996 Thing details: Make link in Thing status description clickable
  bundles/org.openhab.ui/web/src/components/thing/thing-status-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/things/thing-details.vue
Labels: enhancement, main ui

#3005 Developer Dock: Add tooltips to nav buttons
  bundles/org.openhab.ui/web/src/components/developer/developer-dock.vue
Labels: enhancement, main ui

#3009 Thing Add: Validate Thing ID before saving
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
  bundles/org.openhab.ui/web/src/components/thing/thing-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/things/add/thing-add.vue
Labels: enhancement, main ui

#3008 Rule edit: Add descriptions to triggers, actions & conditions sections
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
Labels: enhancement, main ui

#3007 Sitemap treeview: Fix arrows/chevrons shown if not expandable
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/treeview-item.vue
Labels: bug, main ui

#3014 Thing Add: Navigate to the new Thing once added
  bundles/org.openhab.ui/web/src/pages/settings/things/add/thing-add.vue
Labels: enhancement, main ui

#3016 Addons Store: Remove unused searchbar property
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: main ui

#2968 Add level icons to log viewer
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui

#3011 Log viewer: Fixed column width for timestamp, level & logger name
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui

#3024 Page view: Fix title sometimes not centered & Fix Vue warn
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
Labels: bug, main ui

#3022 Update oh-slider handing of steps when rounding state values
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-slider.vue
Labels: bug, main ui

#3026 Log viewer: Align logger name left
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui

#3028 Addons Store: Extend search to the add-on descriptions
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: enhancement, main ui

#3010 Item Add: Navigate to the new Item once added
  bundles/org.openhab.ui/web/src/pages/settings/items/item-edit.vue
Labels: enhancement, main ui

#3034 Link to New Item: Prefix with Thing's label
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-add.vue
Labels: enhancement, main ui

#3031 Tag Input: Fix enter key on Android
  bundles/org.openhab.ui/web/src/components/tags/tag-input.vue
Labels: bug, main ui

#3033 Layout Editor: Fix invisible bottom part of the screen
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-layout-page.vue
Labels: bug, main ui
