Repository openhab/openhab-webui, pull requests merged in 2025-02, with the labels that each got.

#3062 Interactive SVG Canvas: Use percentage state for color state computing
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
Labels: enhancement, main ui

#3059 Thing Validation: Mustn't start with a dash, include dash in error message
  bundles/org.openhab.ui/web/src/components/thing/thing-mixin.js
Labels: bug, main ui

#3055 Sitemap editor: fix negative number parameters
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
Labels: bug, main ui

#3046 oh-image-card: Fix inconsistent image size when action is defined
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-image-card.vue
Labels: bug, main ui

#3053 Addons Store: Show tab bar when left panel is hidden
  bundles/org.openhab.ui/web/src/pages/addons/addons-store.vue
Labels: bug, main ui

#3036 Canvas Layout: Fix embedding SVG errors
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-embedded-svg-mixin.js
  bundles/org.openhab.ui/web/src/components/widgets/layout/oh-canvas-layout.vue
Labels: bug, main ui

#3043 Fix oh-icon icon name type in widget def & docs
  bundles/org.openhab.ui/doc/components/oh-icon.md
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/icon.js
Labels: bug, main ui

#3040 Link Edit: Add dirty checking
  bundles/org.openhab.ui/web/src/pages/settings/things/link/link-edit.vue
Labels: enhancement, main ui

#3044 Tabbed Page: Support Iconify and openHAB icons for tabs
  bundles/org.openhab.ui/web/src/assets/definitions/widgets/tabs/index.js
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/tabs/tabs-edit.vue
Labels: enhancement, main ui

#3045 Item Detail: Fix search in developer sidebar
  bundles/org.openhab.ui/web/src/components/app.vue
Labels: bug, main ui

#3060 UID Input: Add `Fix UID` button to normalize UID input
  bundles/org.openhab.ui/web/src/components/item/item-form.vue
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/components/rule/rule-general-settings.vue
  bundles/org.openhab.ui/web/src/components/thing/thing-general-settings.vue
  bundles/org.openhab.ui/web/src/js/openhab/utils.js
  bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-general-settings.vue
  bundles/org.openhab.ui/web/test/jest/__tests__/utils.test.js
Labels: enhancement, main ui

#3064 Tabbed Page: Fix label too large
  bundles/org.openhab.ui/web/src/pages/page/page-view.vue
Labels: bug, main ui, regression

#3030 [logviewer] Support history
  bundles/org.openhab.ui/web/src/pages/developer/log-viewer.vue
Labels: enhancement, main ui

#3049 Condition Module Wizard: Add Interval condition to Time Condition
  bundles/org.openhab.ui/web/src/components/rule/condition-module-wizard.vue
Labels: enhancement, main ui

#3051 Script edit: Add support for new python add-on & Refactor automation-languages definition
  bundles/org.openhab.ui/web/src/assets/automation-languages.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#3057 Page Settings: Add Copy and Remove Page buttons
  bundles/org.openhab.ui/web/src/components/pagedesigner/page-settings.vue
  bundles/org.openhab.ui/web/src/pages/settings/pages/pagedesigner-mixin.js
Labels: enhancement, main ui

#3065 Fix oh-image-card styling affects all cards
  bundles/org.openhab.ui/web/src/components/widgets/standard/oh-image-card.vue
Labels: bug, main ui, regression

#3066 Upgrade some Main UI dependencies
  bundles/org.openhab.ui/web/package-lock.json
Labels: main ui, dependencies

#3048 Sitemap editor: fix icon parsing error
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
Labels: bug, main ui

#3068 oh-label-cell: Fix issue with setting badge colour
  bundles/org.openhab.ui/web/src/components/widgets/standard/cell/oh-label-cell.vue
Labels: bug, main ui

#3042 Script edit: Display conditions
  bundles/org.openhab.ui/web/src/pages/settings/rules/script/script-edit.vue
Labels: enhancement, main ui

#3074 Downgrade vue-fragment to 1.5.1
  bundles/org.openhab.ui/web/package-lock.json
Labels: bug, main ui, regression
