Repository openhab/openhab-webui, pull requests merged in 2025-07, with the labels that each got.

#3256 oh-slider-item: Respect `ignoreDisplayState` config & Improve docs
  bundles/org.openhab.ui/doc/components/oh-slider-item.md
  bundles/org.openhab.ui/web/src/components/widgets/standard/list/oh-slider-item.vue
Labels: bug, main ui

#3257 oh-slider: Fix display state with decimal comma parsed to integer
  bundles/org.openhab.ui/web/src/components/widgets/system/oh-input.vue
  bundles/org.openhab.ui/web/src/js/app.js
  bundles/org.openhab.ui/web/src/js/monkeypatch.js
Labels: bug, main ui

#3165 Add page to edit semantic tags tree
  bundles/org.openhab.ui/web/src/components/tags/semantics-picker.vue
  bundles/org.openhab.ui/web/src/components/tags/semantics-treeview.vue
  bundles/org.openhab.ui/web/src/components/tags/tag-mixin.js
  bundles/org.openhab.ui/web/src/components/tags/treeview-item.vue
  bundles/org.openhab.ui/web/src/js/routes.js
  bundles/org.openhab.ui/web/src/js/store/modules/semantics.js
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
  bundles/org.openhab.ui/web/src/pages/developer/semantics/semantic-tags-edit.vue
Labels: enhancement, main ui

#3232 Regenerate rule templates: Follow up for #3197
  bundles/org.openhab.ui/web/src/assets/i18n/common/en.json
  bundles/org.openhab.ui/web/src/components/rule/rule-status-mixin.js
  bundles/org.openhab.ui/web/src/pages/settings/rules/rule-edit.vue
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
Labels: main ui

#3263 Transformations List: Fix incorrect counter title
  bundles/org.openhab.ui/web/src/pages/settings/transformations/transformations-list.vue
Labels: bug, main ui

#3268 oh-slider docs: Fix note box not rendered properly
  bundles/org.openhab.ui/doc/components/oh-slider-item.md
  bundles/org.openhab.ui/doc/components/oh-slider.md
Labels: main ui

#3270 Semantic tags maintenance page: Change icon in menu entry
  bundles/org.openhab.ui/web/src/pages/developer/developer-tools.vue
Labels: main ui

#3279 [BasicUI] Add chart option interpolation
  bundles/org.openhab.ui.basic/src/main/java/org/openhab/ui/basic/internal/render/ChartRenderer.java
Labels: enhancement, basic ui

#3298 Sitemap edit: Fix quotes for icon value not allowed
  bundles/org.openhab.ui/web/src/assets/sitemap-lexer.nearley
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/dslUtil_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/__tests__/sitemap-code_jest.spec.js
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/dslUtil.js
Labels: bug, main ui

#3299 Sitemap edit: Fix validation errors for valid buttongrid
  bundles/org.openhab.ui/web/src/components/pagedesigner/sitemap/sitemap-mixin.js
Labels: bug, main ui

#3301 Rules list: Fix styling leaking into global stylesheet
  bundles/org.openhab.ui/web/src/pages/settings/rules/rules-list.vue
Labels: bug, main ui, regression
